import type { 
  AACCategory, 
  AACCard, 
  VisualScene, 
  VisualSceneHotspot, 
  AppSettings 
} from '../../types/index.ts';

export const DEFAULT_SETTINGS: AppSettings = {
    id: 'current',
  theme: 'dark',
  gridCols: 4,
  tapDebounceMs: 300,
  speechRate: 0.9,
  speechPitch: 1.0,
  selectedVoiceURI: '',
  selectedVoiceEnUS: '',
  selectedVoiceZhTW: '',
  cardSpeechLanguage: 'en-then-zh',
  weeklyFocusCardsPerCategory: 2,
  fontSize: 'large',
  googleSheetSyncUrl: 'https://docs.google.com/spreadsheets/d/1MsCXaC6F-uJiiYsqnS4-abW2nFTYFyTMd09hHRfwOwE/edit',
  googleSheetAutoSyncOnLoad: true,
  googleSheetSyncCardsTab: '',
  googleOAuthClientId: '',
  googleOAuthUserEmail: '',
};

export const DEFAULT_CATEGORIES: AACCategory[] = [
  { id: 'cat-needs', name: 'Daily Needs', nameZh: '日常需求', icon: 'HeartHandshake', color: '#86EFAC', order: 1, isDefault: true },
  { id: 'cat-health', name: 'Health', nameZh: '健康身體', icon: 'Activity', color: '#EF4444', order: 2, isDefault: true },
  { id: 'cat-food', name: 'Food & Drink', nameZh: '飲食點心', icon: 'Utensils', color: '#FDBA74', order: 3, isDefault: true },
  { id: 'cat-feelings', name: 'Feelings', nameZh: '心情感受', icon: 'Smile', color: '#93C5FD', order: 4, isDefault: true },
  { id: 'cat-family', name: 'Family', nameZh: '家人親友', icon: 'Users', color: '#FDE047', order: 5, isDefault: true },
  { id: 'cat-time', name: 'Date & Time', nameZh: '時間日期', icon: 'Clock', color: '#67E8F9', order: 6, isDefault: true },
  { id: 'cat-numbers', name: 'Numbers', nameZh: '數字', icon: 'Hash', color: '#F472B6', order: 7, isDefault: true },
  { id: 'cat-activities', name: 'Activities', nameZh: '休閒活動', icon: 'Sparkles', color: '#C4B5FD', order: 8, isDefault: true },
  { id: 'cat-places', name: 'Places', nameZh: '地點場所', icon: 'MapPin', color: '#FCA5A5', order: 9, isDefault: true },
];

export const DEFAULT_CARDS: AACCard[] = [
  // --- Daily Needs ---
  {
    id: 'card-water',
    categoryId: 'cat-needs',
    label: "Water",
    labelZh: "喝水",
    spokenText: "I would like some water, please.",
    spokenTextZh: "我想喝水。",
    definition: "A clear liquid that is essential for life and quenching thirst.",
    definitionZh: "維持生命與解渴所必需的清澈液體。",
    exampleSentence: "He poured a cold glass of water to drink after walking.",
    exampleSentenceZh: "他在散步後倒了一杯溫開水來解渴。",
    phoneticSyllables: "Wa · ter",
    clue: "Pour a cold glass of...",
    clueZh: "口渴時想來一杯清涼的...",
    fitzgeraldCategory: 'nouns',
    icon: "💧",
    order: 1,
    isFavorite: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-bathroom',
    categoryId: 'cat-needs',
    label: "Bathroom",
    labelZh: "洗手間",
    spokenText: "I need to use the bathroom.",
    spokenTextZh: "我想去洗手間。",
    definition: "A private room equipped with a toilet and sink for personal hygiene.",
    definitionZh: "設有馬桶與洗手台、供如廁與個人清潔的盥洗室。",
    exampleSentence: "Excuse me for a moment while I wash my hands in the restroom.",
    exampleSentenceZh: "請稍等一下，我去洗手間洗個手。",
    phoneticSyllables: "Bath · room",
    clue: "Wash your hands and use the toilet in the...",
    clueZh: "洗手或如廁要前往...",
    fitzgeraldCategory: 'emergency',
    icon: "🚻",
    order: 2,
    isFavorite: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-tissue',
    categoryId: 'cat-needs',
    label: "Tissue",
    labelZh: "衛生紙",
    spokenText: "Can you please hand me a tissue?",
    spokenTextZh: "請幫我拿一張衛生紙。",
    definition: "A soft, absorbent piece of disposable paper used for wiping.",
    definitionZh: "用來擦拭雙手、口鼻或臉頰的柔軟吸水紙巾。",
    exampleSentence: "She pulled a soft paper square from the box to wipe her glasses.",
    exampleSentenceZh: "他從面紙盒裡抽出一張柔軟紙巾來擦拭眼鏡。",
    phoneticSyllables: "Tis · sue",
    clue: "Wipe your mouth and nose with a soft...",
    clueZh: "擦擦嘴角需要抽一張...",
    fitzgeraldCategory: 'nouns',
    icon: "🧻",
    order: 3,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-rest',
    categoryId: 'cat-needs',
    label: "Rest",
    labelZh: "休息",
    spokenText: "I would like to sit and rest for a bit.",
    spokenTextZh: "我想坐著休息一下。",
    definition: "To pause activity in order to relax and recover energy.",
    definitionZh: "暫停手邊活動以放鬆身心、恢復體力的狀態。",
    exampleSentence: "After finishing his exercises, he sat comfortably in the armchair to unwind.",
    exampleSentenceZh: "做完伸展復健後，他舒服地坐在沙發上放鬆調養。",
    phoneticSyllables: "Rest",
    clue: "Sit back comfortably on the sofa to take a...",
    clueZh: "閉上雙眼靠在沙發上稍微...",
    fitzgeraldCategory: 'verbs',
    icon: "🛋️",
    order: 4,
    isFavorite: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-sleep',
    categoryId: 'cat-needs',
    label: "Sleep",
    labelZh: "睡覺",
    spokenText: "I am tired and want to go to sleep.",
    spokenTextZh: "我累了想去睡覺。",
    definition: "A natural state of rest during which the body and mind recharge for the next day.",
    definitionZh: "夜晚躺在床上閉目休息、讓大腦與身體完全充電的深層狀態。",
    exampleSentence: "Getting eight hours of quiet slumber helps the brain stay sharp and healthy.",
    exampleSentenceZh: "每晚保持充足深層的閉目靜養，能讓大腦精神飽滿。",
    phoneticSyllables: "Sleep",
    clue: "Lie down in bed under the covers to...",
    clueZh: "躺在舒適的床上閉眼進入夢鄉...",
    fitzgeraldCategory: 'verbs',
    icon: "🛏️",
    order: 5,
    isFavorite: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-blanket',
    categoryId: 'cat-needs',
    label: "Blanket",
    labelZh: "被子",
    spokenText: "I am cold, please give me a blanket.",
    spokenTextZh: "我覺得冷，請給我被子。",
    definition: "A warm piece of soft fabric used as a covering over the body in bed or on a couch.",
    definitionZh: "鋪蓋在身上用來保暖防寒的厚實柔軟織物。",
    exampleSentence: "He wrapped the cozy wool cover over his lap while watching the evening news.",
    exampleSentenceZh: "看電視時，他把溫暖柔軟的毛織蓋被鋪在膝蓋上防涼。",
    phoneticSyllables: "Blan · ket",
    clue: "Cover yourself in bed to stay warm with a...",
    clueZh: "天氣變冷時身上蓋著保暖的...",
    fitzgeraldCategory: 'nouns',
    icon: "🧶",
    order: 6,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-reposition',
    categoryId: 'cat-needs',
    label: "Reposition",
    labelZh: "調整姿勢",
    spokenText: "Please help me adjust my seating position.",
    spokenTextZh: "請幫我調整一下姿勢。",
    definition: "To adjust your sitting or lying posture for better comfort and blood circulation.",
    definitionZh: "調整坐姿或躺臥角度，以減輕壓迫並促進血液循環。",
    exampleSentence: "The caregiver helped shift his pillows so his back was fully supported.",
    exampleSentenceZh: "照護者幫忙挪動枕頭與靠墊，讓背部支撐得更加舒適。",
    phoneticSyllables: "Re · po · si · tion",
    clue: "Shift your body and turn in bed to...",
    clueZh: "躺久了身體不舒服需要稍微...",
    fitzgeraldCategory: 'verbs',
    icon: "🔄",
    order: 7,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-temp-hot',
    categoryId: 'cat-needs',
    label: "Too Hot",
    labelZh: "太熱了",
    spokenText: "I feel too hot, can we turn on the fan or AC?",
    spokenTextZh: "我覺得太熱了，可以開電風扇或冷氣嗎？",
    definition: "A sensation of uncomfortably high environmental temperature causing sweating.",
    definitionZh: "環境氣溫過高令人悶熱出汗的不適感覺。",
    exampleSentence: "The afternoon sunshine made the room very warm, so we turned on the fan.",
    exampleSentenceZh: "午後陽光讓客廳溫度偏高，我們打開了電風扇通風。",
    phoneticSyllables: "Too · Hot",
    clue: "Turn on the cool fan because the room is...",
    clueZh: "一直流汗需要吹電風扇因為...",
    fitzgeraldCategory: 'adjectives',
    icon: "🥵",
    order: 8,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-temp-cold',
    categoryId: 'cat-needs',
    label: "Too Cold",
    labelZh: "太冷了",
    spokenText: "I feel cold, please help me stay warm.",
    spokenTextZh: "我覺得太冷了，請幫我保暖。",
    definition: "A sensation of low environmental temperature causing shivering or chills.",
    definitionZh: "氣溫偏低、令人起雞皮疙瘩或發抖的寒冷感覺。",
    exampleSentence: "A chilly autumn draft came through the window, so he put on a sweater.",
    exampleSentenceZh: "窗外吹來一陣涼風，他穿上一件厚毛衣保暖。",
    phoneticSyllables: "Too · Cold",
    clue: "Put on a thick jacket because the room is...",
    clueZh: "身體直發抖需要穿外套因為...",
    fitzgeraldCategory: 'adjectives',
    icon: "🥶",
    order: 9,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-repair-time',
    categoryId: 'cat-needs',
    label: "Give Me Time",
    labelZh: "請給我時間",
    spokenText: "Please give me a moment, let me try to say it.",
    spokenTextZh: "請給我一點時間，讓我想一下慢慢說。",
    definition: "A polite request asking listeners for patience while you prepare your words.",
    definitionZh: "請談話對象耐心等候、讓自己有充裕時間組織言語的禮貌表達。",
    exampleSentence: "He raised a gentle hand to signal that he needed a few moments to think.",
    exampleSentenceZh: "他輕輕舉手示意，表示需要稍作思考再慢慢回答。",
    phoneticSyllables: "Give · Me · Time",
    clue: "Please be patient and do not rush me,...",
    clueZh: "請不要催促我，慢慢來...",
    fitzgeraldCategory: 'social',
    icon: "⏳",
    order: 10,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-repair-repeat',
    categoryId: 'cat-needs',
    label: "Say Again",
    labelZh: "請再說一次",
    spokenText: "Could you please repeat that for me?",
    spokenTextZh: "請你再說一次好嗎？",
    definition: "A request asking a speaker to state their words once more for clarity.",
    definitionZh: "請對方把剛才說過的話重新講一遍以便聽清楚的請求。",
    exampleSentence: "Because the background music was loud, he asked his son to speak the words once more.",
    exampleSentenceZh: "因為客廳有些雜音，他請兒子把剛剛的話重新說明一次。",
    phoneticSyllables: "Say · A · gain",
    clue: "I did not catch what you said, please...",
    clueZh: "剛剛沒聽清楚您的話，...",
    fitzgeraldCategory: 'verbs',
    icon: "🔁",
    order: 11,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-quick-yes',
    categoryId: 'cat-needs',
    label: "Yes",
    labelZh: "好",
    spokenText: "Yes.",
    spokenTextZh: "好的。",
    definition: "An affirmative expression used to show agreement, approval, or acceptance.",
    definitionZh: "表示贊同、答應、同意或接受的肯定回應。",
    exampleSentence: "When asked if he wanted soup with lunch, he nodded in cheerful agreement.",
    exampleSentenceZh: "當被問到午餐想不想喝熱湯時，他點頭表示贊成。",
    phoneticSyllables: "Yes",
    clue: "Nod your head in agreement to say...",
    clueZh: "點點頭表示答應與同意說聲...",
    fitzgeraldCategory: 'social',
    icon: "👍",
    order: 12,
    isFavorite: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-quick-no',
    categoryId: 'cat-needs',
    label: "No",
    labelZh: "不要",
    spokenText: "No, thank you.",
    spokenTextZh: "不要，謝謝。",
    definition: "A negative expression used to decline an offer, refuse, or indicate disagreement.",
    definitionZh: "表示拒絕、不同意或不需要的否定回應。",
    exampleSentence: "He shook his head gently to indicate that he did not want more coffee.",
    exampleSentenceZh: "他輕輕搖頭，表示現在不需要再添咖啡。",
    phoneticSyllables: "No",
    clue: "Shake your head in disagreement to say...",
    clueZh: "搖搖頭表示拒絕不想做說聲...",
    fitzgeraldCategory: 'social',
    icon: "👎",
    order: 13,
    isFavorite: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-quick-more',
    categoryId: 'cat-needs',
    label: "More",
    labelZh: "還要",
    spokenText: "I would like more, please.",
    spokenTextZh: "我還要。",
    definition: "A request indicating a desire for an additional amount or further portion of something.",
    definitionZh: "表示希望增加數量、再來一份或繼續進行的請求。",
    exampleSentence: "He enjoyed the fruit so much that he asked for an extra small dish.",
    exampleSentenceZh: "這道水果非常甜，他希望能夠再添一些。",
    phoneticSyllables: "More",
    clue: "Having another delicious serving because you want...",
    clueZh: "這道料理真美味，我想要...",
    fitzgeraldCategory: 'adjectives',
    icon: "➕",
    order: 14,
    isFavorite: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-quick-done',
    categoryId: 'cat-needs',
    label: "All Done",
    labelZh: "好了",
    spokenText: "I am all done.",
    spokenTextZh: "我已經好了。",
    definition: "An expression indicating that a task, meal, or activity is completely finished.",
    definitionZh: "表示某項活動、用餐或手邊任務已經完全結束。",
    exampleSentence: "He put his spoon down on the plate to show that his meal was complete.",
    exampleSentenceZh: "他把湯匙放回餐盤上，示意這頓飯已經全部享用完畢。",
    phoneticSyllables: "All · Done",
    clue: "Finished with our task and completely...",
    clueZh: "事情都順利完成、全部都...",
    fitzgeraldCategory: 'social',
    icon: "🏁",
    order: 15,
    isFavorite: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  // --- Health ---
  {
    id: 'card-pain',
    categoryId: 'cat-health',
    label: "I Have Pain",
    labelZh: "我會痛",
    spokenText: "I am experiencing pain right now.",
    spokenTextZh: "我現在覺得痛。",
    definition: "An unpleasant physical sensation caused by illness, injury, or muscle tension.",
    definitionZh: "因身體不適、受傷或肌肉緊繃所產生的難受刺痛感。",
    exampleSentence: "He pointed to his lower back to let the nurse know where it was hurting.",
    exampleSentenceZh: "他指了指自己的下背部，讓護理人員知道哪裡感到不舒服。",
    phoneticSyllables: "Pain",
    clue: "Pointing to where it hurts because...",
    clueZh: "手指著不舒服發痠的部位表示...",
    fitzgeraldCategory: 'emergency',
    icon: "⚡",
    order: 1,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-medicine',
    categoryId: 'cat-health',
    label: "Medicine",
    labelZh: "吃藥",
    spokenText: "Is it time for my medication?",
    spokenTextZh: "該吃藥了嗎？",
    definition: "A substance or pill taken to prevent, cure, or relieve symptoms of an illness.",
    definitionZh: "用來預防、治療疾病或減輕身體不適的藥劑或藥丸。",
    exampleSentence: "He takes his daily blood pressure pills with a glass of water after breakfast.",
    exampleSentenceZh: "早餐後他配著溫開水服用每天按時服用的處方藥物。",
    phoneticSyllables: "Med · i · cine",
    clue: "Swallow your prescribed pills and...",
    clueZh: "時間到了該按時吞服護理師給的...",
    fitzgeraldCategory: 'nouns',
    icon: "💊",
    order: 2,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-dizzy',
    categoryId: 'cat-health',
    label: "Dizzy",
    labelZh: "頭暈",
    spokenText: "I am feeling dizzy and lightheaded.",
    spokenTextZh: "我感覺有點頭暈。",
    definition: "A feeling of spinning, unsteadiness, or lightheadedness in the head.",
    definitionZh: "頭部感到天旋地轉、昏沉或站不穩的眩暈感受。",
    exampleSentence: "Standing up too quickly made him feel lightheaded, so he sat down until it passed.",
    exampleSentenceZh: "起身太快時感覺周遭在旋轉，他趕緊坐下緩解暈眩。",
    phoneticSyllables: "Diz · zy",
    clue: "Feeling lightheaded as if the room is spinning and...",
    clueZh: "感覺天旋地轉站不穩、腦袋一陣...",
    fitzgeraldCategory: 'adjectives',
    icon: "💫",
    order: 3,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-numbness',
    categoryId: 'cat-health',
    label: "Numbness",
    labelZh: "發麻",
    spokenText: "My arm or leg feels numb.",
    spokenTextZh: "我的手腳感覺發麻。",
    definition: "A loss of normal physical sensation or a tingling pins-and-needles feeling in a limb.",
    definitionZh: "肢體感覺遲鈍、暫時喪失知覺或如針刺般的麻木感。",
    exampleSentence: "Sitting in one position caused a tingling pins-and-needles sensation in his left foot.",
    exampleSentenceZh: "保持同一姿勢太久讓他的左腳掌傳來一陣陣針刺般的發木感。",
    phoneticSyllables: "Numb · ness",
    clue: "Tingling loss of sensation in your fingertips like...",
    clueZh: "手腳一陣陣針扎刺痛且感覺...",
    fitzgeraldCategory: 'adjectives',
    icon: "🧊",
    order: 4,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-weak',
    categoryId: 'cat-health',
    label: "Weak",
    labelZh: "沒力氣",
    spokenText: "I feel weak and have no strength in my muscles.",
    spokenTextZh: "我覺得手腳沒力氣。",
    definition: "Lacking physical strength, energy, or muscle power.",
    definitionZh: "身體缺乏力量、肌肉使不上勁或感到虛弱無力的狀態。",
    exampleSentence: "His arms felt tired after the long therapy workout, so he took a break.",
    exampleSentenceZh: "經過長時間的肢體鍛鍊後，他的手臂感覺沉重使不上勁。",
    phoneticSyllables: "Weak",
    clue: "Having no energy in your limbs and feeling physically...",
    clueZh: "手腳疲軟使不上勁、全身軟綿綿...",
    fitzgeraldCategory: 'adjectives',
    icon: "🥀",
    order: 5,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-doctor',
    categoryId: 'cat-health',
    label: "Doctor",
    labelZh: "醫生",
    spokenText: "Please call the doctor.",
    spokenTextZh: "請幫我找醫生。",
    definition: "A licensed medical professional qualified to diagnose and treat health conditions.",
    definitionZh: "具備專業醫療資格、負責診斷與治療疾病的醫師。",
    exampleSentence: "The physician listened carefully to his heartbeat with a stethoscope during the checkup.",
    exampleSentenceZh: "門診檢查時，醫師拿著聽診器仔細聆聽他的心跳與呼吸。",
    phoneticSyllables: "Doc · tor",
    clue: "The medical physician in a white coat with a stethoscope is the...",
    clueZh: "穿著白袍拿著聽診器親切問診的主治...",
    fitzgeraldCategory: 'people',
    icon: "👨‍⚕️",
    order: 6,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-nurse',
    categoryId: 'cat-health',
    label: "Nurse",
    labelZh: "護理師",
    spokenText: "Please call the nurse for assistance.",
    spokenTextZh: "請幫我叫護理師。",
    definition: "A trained healthcare professional who cares for sick or injured people and administers care.",
    definitionZh: "受過專業醫療照護訓練、負責量血壓給藥並細心照料病患的專業人員。",
    exampleSentence: "The clinical assistant gently checked his blood pressure and pulse each morning.",
    exampleSentenceZh: "專業照護師每天早晨都會親切地幫他量測血壓與脈搏。",
    phoneticSyllables: "Nurse",
    clue: "The caring healthcare professional checking your vitals is the...",
    clueZh: "親切量測血壓心跳與照料日常的白衣天使...",
    fitzgeraldCategory: 'people',
    icon: "👩‍⚕️",
    order: 7,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-quick-help',
    categoryId: 'cat-health',
    label: "Help",
    labelZh: "請幫我",
    spokenText: "Please help me.",
    spokenTextZh: "請幫我一下。",
    definition: "An urgent request for another person to provide physical or practical assistance.",
    definitionZh: "需要他人伸出援手或提供即時協助的緊急求助請求。",
    exampleSentence: "He called out to his family when he needed someone to help him stand up safely.",
    exampleSentenceZh: "需要從椅子站起身時，他向身旁的家人示意伸出雙手給予扶持。",
    phoneticSyllables: "Help",
    clue: "Calling out when you need immediate assistance for someone to...",
    clueZh: "遇到緊急狀況需要大家伸出援手時呼喚...",
    fitzgeraldCategory: 'emergency',
    icon: "🆘",
    order: 8,
    isFavorite: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  // --- Food & Drink ---
  {
    id: 'card-breakfast',
    categoryId: 'cat-food',
    label: "Breakfast",
    labelZh: "早餐",
    spokenText: "I would like to have breakfast.",
    spokenTextZh: "我想吃早餐。",
    definition: "The first meal of the day, typically eaten in the morning hours.",
    definitionZh: "一天當中的第一餐，通常在早晨起床後享用。",
    exampleSentence: "He enjoyed warm oatmeal, fresh toast, and milk to start his morning.",
    exampleSentenceZh: "他早晨享用了一碗熱燕麥粥配烤吐司，開啟活力的一天。",
    phoneticSyllables: "Break · fast",
    clue: "The first meal of the morning with eggs and toast is...",
    clueZh: "早晨起床後享用的第一頓餐點是...",
    fitzgeraldCategory: 'nouns',
    icon: "🥞",
    order: 1,
    isFavorite: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-lunch',
    categoryId: 'cat-food',
    label: "Lunch",
    labelZh: "午餐",
    spokenText: "I would like to have lunch.",
    spokenTextZh: "我想吃午餐。",
    definition: "A midday meal eaten in the middle of the day.",
    definitionZh: "在中午時段享用的正餐。",
    exampleSentence: "At noontime, the family gathered around the table to eat warm noodle soup.",
    exampleSentenceZh: "正中午時分，全家人圍坐在餐桌旁一起享用熱騰騰的麵食。",
    phoneticSyllables: "Lunch",
    clue: "The midday meal eaten around noon is...",
    clueZh: "正中午十二點鐘享用的正餐是...",
    fitzgeraldCategory: 'nouns',
    icon: "🥪",
    order: 2,
    isFavorite: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-dinner',
    categoryId: 'cat-food',
    label: "Dinner",
    labelZh: "晚餐",
    spokenText: "I would like to have dinner.",
    spokenTextZh: "我想吃晚餐。",
    definition: "The main evening meal shared with family at the end of the day.",
    definitionZh: "傍晚或夜晚全家團聚享用的一天當中最後一頓豐盛正餐。",
    exampleSentence: "In the evening, they enjoyed steamed fish and rice together around the table.",
    exampleSentenceZh: "傍晚時分，大家齊聚客廳餐桌享用鮮魚與香噴噴的佳餚。",
    phoneticSyllables: "Din · ner",
    clue: "The evening meal eaten with family after sunset is...",
    clueZh: "傍晚全家人圍在餐桌前享用的傍晚盛宴是...",
    fitzgeraldCategory: 'nouns',
    icon: "🍲",
    order: 3,
    isFavorite: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-hungry',
    categoryId: 'cat-food',
    label: "Hungry",
    labelZh: "肚子餓",
    spokenText: "I am hungry and ready to eat.",
    spokenTextZh: "我肚子餓了，想吃東西。",
    definition: "Feeling a natural physical need or strong desire to eat food.",
    definitionZh: "胃部空空的、感到需要進食補充能量的飢餓生理感覺。",
    exampleSentence: "After his afternoon walk, his stomach rumbled and he was ready for a snack.",
    exampleSentenceZh: "下午散步後肚子咕嚕咕嚕叫，他感覺胃口大開想吃點心。",
    phoneticSyllables: "Hun · gry",
    clue: "Your stomach is rumbling for a meal because you feel...",
    clueZh: "到了用餐時間腸胃咕嚕嚕叫表示...",
    fitzgeraldCategory: 'adjectives',
    icon: "🍽️",
    order: 4,
    isFavorite: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-thirsty',
    categoryId: 'cat-food',
    label: "Thirsty",
    labelZh: "口渴",
    spokenText: "I am very thirsty.",
    spokenTextZh: "我口渴了。",
    definition: "Feeling a dry sensation in the mouth and throat indicating a need for liquid.",
    definitionZh: "喉嚨與口腔乾燥、急需飲水解渴的生理感覺。",
    exampleSentence: "Working in the warm sunshine made his throat dry, so he reached for his cup.",
    exampleSentenceZh: "在陽光下活動後喉嚨乾燥，他拿起水杯大口喝水。",
    phoneticSyllables: "Thirs · ty",
    clue: "Your dry throat is craving a drink of water because you are...",
    clueZh: "喉嚨乾澀想喝一大杯水因為感到...",
    fitzgeraldCategory: 'adjectives',
    icon: "🥤",
    order: 5,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-rice',
    categoryId: 'cat-food',
    label: "Meal",
    labelZh: "吃飯",
    spokenText: "I would like to have a meal.",
    spokenTextZh: "請準備飯菜，我想吃飯。",
    definition: "A staple grain boiled or steamed in water, serving as the foundation of daily meals.",
    definitionZh: "經蒸煮熟透、粒粒分明的穀物主食，為亞洲家庭餐桌的核心。",
    exampleSentence: "A warm bowl of fluffy white grains was served alongside savory stir-fried dishes.",
    exampleSentenceZh: "熱氣騰騰的白皙米粒盛在碗中，搭配美味家常菜餚一起享用。",
    phoneticSyllables: "Meal",
    clue: "Sit at the dining table with a bowl and spoon to enjoy your...",
    clueZh: "拿起碗筷坐在餐桌前準備大口...",
    fitzgeraldCategory: 'nouns',
    icon: "🍚",
    order: 6,
    isFavorite: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-pork',
    categoryId: 'cat-food',
    label: "Pork",
    labelZh: "豬肉",
    spokenText: "I would like some pork, please.",
    spokenTextZh: "我想吃豬肉。",
    definition: "Culinary meat derived from domestic pigs, often braised or stir-fried.",
    definitionZh: "來自豬隻的肉品，常用於滷肉、炒肉絲或燉湯等家常菜餚。",
    exampleSentence: "Dad enjoyed the tender braised loin simmered with sweet soy sauce and garlic.",
    exampleSentenceZh: "爸爸特別喜愛用醬油與大蒜慢火燉煮得軟嫩入味的滷五花肉。",
    phoneticSyllables: "Pork",
    clue: "Savory meat from a pig cooked tender is...",
    clueZh: "餐桌上香噴噴的排骨或肉絲是紅燒...",
    fitzgeraldCategory: 'nouns',
    icon: "🥩",
    order: 7,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-beef',
    categoryId: 'cat-food',
    label: "Beef",
    labelZh: "牛肉",
    spokenText: "I would like some beef, please.",
    spokenTextZh: "我想吃牛肉。",
    definition: "Culinary meat derived from cattle, rich in protein and iron.",
    definitionZh: "來自牛隻的肉品，富含優質蛋白質與鐵質，常用於燉湯或快炒。",
    exampleSentence: "The hot broth was filled with soft slices of steak and fresh scallions.",
    exampleSentenceZh: "熱騰騰的湯碗裡盛滿了鮮嫩多汁的燉肉塊與蔥花。",
    phoneticSyllables: "Beef",
    clue: "Hearty red meat from cattle served in a steak is...",
    clueZh: "夜市滋滋作響的鐵板排餐或麵食是香煎...",
    fitzgeraldCategory: 'nouns',
    icon: "🥩",
    order: 8,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-chicken',
    categoryId: 'cat-food',
    label: "Chicken",
    labelZh: "雞肉",
    spokenText: "I would like some chicken, please.",
    spokenTextZh: "我想吃雞肉。",
    definition: "Culinary poultry meat that is lean, tender, and versatile in cooking.",
    definitionZh: "來自家禽雞隻的白肉，肉質細嫩清淡，適合煮湯、香煎或蒸煮。",
    exampleSentence: "A bowl of warm broth simmered with tender poultry and ginger warmed his chest.",
    exampleSentenceZh: "加入老薑慢火細燉的香濃禽肉鮮湯，喝下去令人暖心暖胃。",
    phoneticSyllables: "Chick · en",
    clue: "Tender poultry drumsticks roasted golden brown are...",
    clueZh: "金黃酥脆的炸腿排與香菇燉湯是香噴噴...",
    fitzgeraldCategory: 'nouns',
    icon: "🍗",
    order: 9,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-fish',
    categoryId: 'cat-food',
    label: "Fish",
    labelZh: "魚肉",
    spokenText: "I would like some fish, please.",
    spokenTextZh: "我想吃魚肉。",
    definition: "Healthy seafood rich in omega-3 oils, often steamed with ginger and scallions.",
    definitionZh: "富含優質油脂與蛋白質的水生海鮮食材，常以清蒸或乾煎烹調。",
    exampleSentence: "The steamed sea bass with ginger slices flaked apart tenderly on his fork.",
    exampleSentenceZh: "加了薑絲與青蔥清蒸的鮮美海產，肉質細緻入口即化。",
    phoneticSyllables: "Fish",
    clue: "Seafood swimming in the ocean served with lemon is fresh...",
    clueZh: "清蒸新鮮海鮮料理淋上薑絲蔥花是鮮甜...",
    fitzgeraldCategory: 'nouns',
    icon: "🐟",
    order: 10,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-soup',
    categoryId: 'cat-food',
    label: "Soup",
    labelZh: "喝湯",
    spokenText: "Some warm soup sounds good.",
    spokenTextZh: "我想喝點熱湯。",
    definition: "A warm liquid dish made by simmering meat, vegetables, and seasoning in water.",
    definitionZh: "將肉類、蔬菜與香料食材慢火熬煮而成、溫熱滋補的美味湯品。",
    exampleSentence: "He lifted the porcelain spoon to sip the clear vegetable and chicken broth.",
    exampleSentenceZh: "他拿起湯匙舀起一匙清澈甘甜的蔬菜雞高湯慢慢品嘗。",
    phoneticSyllables: "Soup",
    clue: "Sip a warm, comforting broth from a bowl with a spoon like...",
    clueZh: "端起熱呼呼的香濃高湯用湯匙舀來...",
    fitzgeraldCategory: 'nouns',
    icon: "🥣",
    order: 11,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-salad',
    categoryId: 'cat-food',
    label: "Salad",
    labelZh: "沙拉",
    spokenText: "I would like some salad, please.",
    spokenTextZh: "我想吃沙拉。",
    definition: "A dish of raw or lightly cooked crisp vegetables tossed with dressing.",
    definitionZh: "由多種新鮮脆嫩生菜與蔬菜搭配醬汁拌勻而成的清爽冷盤。",
    exampleSentence: "Crisp green lettuce, ripe tomatoes, and cucumber were tossed in olive oil.",
    exampleSentenceZh: "鮮脆的綠萵苣、紅番茄與小黃瓜淋上橄欖油，爽脆可口。",
    phoneticSyllables: "Sal · ad",
    clue: "A healthy bowl of crisp fresh greens, carrots, and dressing is a...",
    clueZh: "滿滿一碗新鮮脆嫩蔬菜拌入香甜油醋醬是爽口...",
    fitzgeraldCategory: 'nouns',
    icon: "🥗",
    order: 12,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-fruit',
    categoryId: 'cat-food',
    label: "Fruit",
    labelZh: "水果",
    spokenText: "Can I have some fruit, please?",
    spokenTextZh: "我想吃點水果。",
    definition: "The sweet, juicy, seed-bearing structure of a plant eaten as a healthy treat.",
    definitionZh: "植物所結出、多汁甘甜且富含維生素的天然產物。",
    exampleSentence: "Sweet slices of golden apple and ripe banana made a refreshing dessert.",
    exampleSentenceZh: "切成薄片的香甜蘋果與成熟香蕉，是飯後最棒的健康甜點。",
    phoneticSyllables: "Fruit",
    clue: "Sweet fresh apples, bananas, and juicy oranges are healthy...",
    clueZh: "香甜多汁的蘋果、香蕉與橘子都是新鮮...",
    fitzgeraldCategory: 'nouns',
    icon: "🍎",
    order: 13,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-warm-water',
    categoryId: 'cat-food',
    label: "Warm Water",
    labelZh: "溫開水",
    spokenText: "Please give me a cup of warm water.",
    spokenTextZh: "請給我一杯溫開水。",
    definition: "Water heated to a mild, soothing temperature that is comfortable to drink.",
    definitionZh: "加溫至適當舒適溫度、不燙口且溫潤喉嚨的飲用水。",
    exampleSentence: "He prefers a thermos mug of soothing heated liquid first thing in the morning.",
    exampleSentenceZh: "早晨起床時，他喜歡先喝一杯保溫杯中溫潤舒服的溫熱飲品。",
    phoneticSyllables: "Warm · Wa · ter",
    clue: "Soothing temperature drink that is neither boiling nor iced is...",
    clueZh: "保溫瓶裡溫度剛好不燙口的解渴飲品是...",
    fitzgeraldCategory: 'nouns',
    icon: "🍵",
    order: 14,
    isFavorite: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-coffee',
    categoryId: 'cat-food',
    label: "Coffee",
    labelZh: "咖啡",
    spokenText: "I would love a warm cup of coffee, please.",
    spokenTextZh: "我想喝杯溫咖啡。",
    definition: "A dark, aromatic brewed beverage made from roasted coffee beans.",
    definitionZh: "由烘焙研磨豆子沖泡而成、香氣濃郁且能提神的深色飲品。",
    exampleSentence: "The rich aroma of a freshly brewed morning cup filled the kitchen.",
    exampleSentenceZh: "廚房裡瀰漫著早晨現煮深色熱飲的迷人濃郁香氣。",
    phoneticSyllables: "Cof · fee",
    clue: "Brew a dark, rich aromatic morning mug of roasted...",
    clueZh: "早晨飄散濃郁烘焙香氣的提神熱飲是黑...",
    fitzgeraldCategory: 'nouns',
    icon: "☕",
    order: 15,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-tea',
    categoryId: 'cat-food',
    label: "Tea",
    labelZh: "茶",
    spokenText: "I would love a warm cup of tea, please.",
    spokenTextZh: "我想喝杯溫茶。",
    definition: "A fragrant hot drink prepared by steeping cured leaves in boiling water.",
    definitionZh: "將乾燥茶葉浸泡在熱水中萃取出的清香甘醇飲品。",
    exampleSentence: "He poured golden oolong brew into a small ceramic cup to sip after lunch.",
    exampleSentenceZh: "午餐後他將金黃色澤的高山烏龍茶湯倒入小瓷杯中慢慢品味。",
    phoneticSyllables: "Tea",
    clue: "Brew aromatic dried herbs in a boiling kettle for a cup of hot...",
    clueZh: "用熱水沖泡芳香回甘的綠葉端上熱呼呼的...",
    fitzgeraldCategory: 'nouns',
    icon: "🍵",
    order: 16,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-milk',
    categoryId: 'cat-food',
    label: "Milk",
    labelZh: "牛奶",
    spokenText: "I would like some milk, please.",
    spokenTextZh: "我想喝牛奶。",
    definition: "A nutrient-rich white liquid produced by mammals, high in calcium.",
    definitionZh: "乳白色富含鈣質與蛋白質的營養飲品，有助於骨骼健康。",
    exampleSentence: "He drank a glass of creamy white beverage to get his daily calcium.",
    exampleSentenceZh: "每天早晨他都會喝上一杯乳白色、富含鈣質的營養飲品。",
    phoneticSyllables: "Milk",
    clue: "Pour a nutritious white dairy drink rich in calcium like...",
    clueZh: "倒一杯乳白色富含鈣質的營養純...",
    fitzgeraldCategory: 'nouns',
    icon: "🥛",
    order: 17,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-cut-food',
    categoryId: 'cat-food',
    label: "Cut Small Pieces",
    labelZh: "切小塊一點",
    spokenText: "Please cut the food into smaller pieces for me.",
    spokenTextZh: "請幫我把食物切小塊一點。",
    definition: "A request to divide a meal into smaller bite-sized portions for easier chewing and swallowing.",
    definitionZh: "將餐盤中的食物切成更小塊以便咀嚼與安全吞嚥的請求。",
    exampleSentence: "The family cut his meat and vegetables into small squares so he could swallow comfortably.",
    exampleSentenceZh: "家人將餐盤裡的肉塊與蔬菜細心剪成一口大小，方便安全吞嚥。",
    phoneticSyllables: "Cut · Small · Piec · es",
    clue: "Use a knife to chop food into bite-sized portions so please...",
    clueZh: "食物太大塊吞嚥困難，請幫我...",
    fitzgeraldCategory: 'verbs',
    icon: "🔪",
    order: 18,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-too-hot',
    categoryId: 'cat-food',
    label: "Too Hot",
    labelZh: "太燙了",
    spokenText: "This is too hot, please let it cool down.",
    spokenTextZh: "這個太燙了，請放涼一點。",
    definition: "Describing food or beverage whose thermal temperature is too high to consume safely.",
    definitionZh: "形容食物或湯品溫度過高、容易燙傷舌頭而需要稍微放涼。",
    exampleSentence: "Steam was billowing from the soup bowl, so he blew on his spoon to cool it down.",
    exampleSentenceZh: "熱湯冒著陣陣白煙，他輕輕吹氣讓溫度稍微降下來。",
    phoneticSyllables: "Too · Hot",
    clue: "Blow on steaming soup before tasting because the temperature is...",
    clueZh: "剛出爐冒著白煙的熱湯請吹一吹因為...",
    fitzgeraldCategory: 'adjectives',
    icon: "♨️",
    order: 19,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-too-cold',
    categoryId: 'cat-food',
    label: "Warm Up",
    labelZh: "幫我加熱",
    spokenText: "This is cold, can you please warm it up?",
    spokenTextZh: "這個變冷了，可以幫我加熱嗎？",
    definition: "A request to reheat a dish that has lost its warmth.",
    definitionZh: "餐盤中的菜餚已經冷卻變涼、希望能重新放入微波爐加溫的請求。",
    exampleSentence: "Since the stew had cooled down, he asked for it to be placed in the microwave for a minute.",
    exampleSentenceZh: "因為菜餚放久了有點冷掉，他請家人幫忙放進微波爐加熱一分鐘。",
    phoneticSyllables: "Warm · Up",
    clue: "Put the chilled dish in the microwave oven to...",
    clueZh: "飯菜放久變冰涼了，請放進微波爐...",
    fitzgeraldCategory: 'adjectives',
    icon: "❄️",
    order: 20,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-delicious',
    categoryId: 'cat-food',
    label: "Delicious",
    labelZh: "很好吃",
    spokenText: "This food is very delicious, thank you!",
    spokenTextZh: "這個很好吃，謝謝！",
    definition: "Giving high praise to the wonderful flavor and taste of food.",
    definitionZh: "稱讚食物香氣四溢、滋味極佳且令人大飽口福的讚美。",
    exampleSentence: "He smiled and gave a thumbs up to express how much he loved the home-cooked meal.",
    exampleSentenceZh: "他豎起大拇指露出滿意微笑，稱讚這頓家常手藝非常合胃口。",
    phoneticSyllables: "De · li · cious",
    clue: "This home-cooked recipe tastes amazing and truly...",
    clueZh: "這盤家常菜色香味俱全、品嚐起來...",
    fitzgeraldCategory: 'social',
    icon: "😋",
    order: 21,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-full',
    categoryId: 'cat-food',
    label: "Full",
    labelZh: "吃飽了",
    spokenText: "I am full and all done eating, thank you.",
    spokenTextZh: "我吃飽了，謝謝。",
    definition: "Having eaten enough food to satisfy hunger completely.",
    definitionZh: "肚子已經填飽、感到滿足且不需要再進食的飽足狀態。",
    exampleSentence: "He leaned back with a contented sigh and set his napkin down on the table.",
    exampleSentenceZh: "他心滿意足地靠在椅背上放下餐具，表示肚子已經裝不下了。",
    phoneticSyllables: "Full",
    clue: "Putting your fork down after a satisfying meal because you are...",
    clueZh: "碗裡的美味佳餚全部吃光光，肚子已經...",
    fitzgeraldCategory: 'social',
    icon: "✋",
    order: 22,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  // --- Feelings ---
  {
    id: 'card-good-morning',
    categoryId: 'cat-feelings',
    label: "Good Morning",
    labelZh: "早安",
    spokenText: "Good morning! Hope you have a wonderful day.",
    spokenTextZh: "早安！祝你有美好的一天。",
    definition: "A cheerful, friendly greeting spoken when meeting someone in the early morning.",
    definitionZh: "清晨剛起床或在早晨遇見他人時所說的親切問候。",
    exampleSentence: "He greeted his daughter with a warm smile as the early sunshine entered the kitchen.",
    exampleSentenceZh: "當清晨第一道陽光灑進客廳時，他微笑著向剛起床的女兒打招呼。",
    phoneticSyllables: "Good · Morn · ing",
    clue: "Greet your family as the sun rises with a cheerful...",
    clueZh: "清晨看見家人起床帶著微笑親切問候一聲...",
    fitzgeraldCategory: 'social',
    icon: "🌅",
    order: 1,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-good-night',
    categoryId: 'cat-feelings',
    label: "Good Night",
    labelZh: "晚安",
    spokenText: "Good night, see you tomorrow.",
    spokenTextZh: "晚安，明天見。",
    definition: "A kind farewell wishing someone peaceful rest before they go to bed.",
    definitionZh: "夜晚臨睡前向家人或親友道別、祝願一夜好眠的溫馨祝福。",
    exampleSentence: "Before turning off the bedside reading lamp, he wished his family sweet dreams.",
    exampleSentenceZh: "關掉床頭燈準備入眠前，他向身邊的家人互道祝願好夢。",
    phoneticSyllables: "Good · Night",
    clue: "Wish your family sweet dreams before closing your eyes with...",
    clueZh: "睡前熄燈互祝美夢安穩入眠說聲...",
    fitzgeraldCategory: 'social',
    icon: "🌙",
    order: 2,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-how-are-you',
    categoryId: 'cat-feelings',
    label: "How Are You?",
    labelZh: "你好嗎？",
    spokenText: "How are you doing today?",
    spokenTextZh: "你今天好嗎？",
    definition: "A caring inquiry asking someone about their health, mood, and well-being.",
    definitionZh: "關心對方的身體狀況、心情與生活近況的親切問候句。",
    exampleSentence: "When his son walked in the door, he asked about his day with genuine care.",
    exampleSentenceZh: "當兒子推開家門走進客廳，他親切地開口關心兒子今天的狀況。",
    phoneticSyllables: "How · Are · You",
    clue: "Ask your friend with a warm smile about their well-being,...",
    clueZh: "看見好久不見的老朋友親切寒暄關心...",
    fitzgeraldCategory: 'questions',
    icon: "👋",
    order: 3,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-happy',
    categoryId: 'cat-feelings',
    label: "Happy",
    labelZh: "開心",
    spokenText: "I am feeling happy today.",
    spokenTextZh: "我今天心情很好很開心。",
    definition: "Feeling or showing pleasure, contentment, and joyful cheer.",
    definitionZh: "內心感到愉悅、舒暢、喜悅與滿足的正向情緒。",
    exampleSentence: "Seeing his grandchildren playing in the living room brought a joyful glow to his eyes.",
    exampleSentenceZh: "看著孫子孫女在客廳活潑玩耍，他的臉上洋溢著無比喜悅的笑容。",
    phoneticSyllables: "Hap · py",
    clue: "Smiling broadly with joyful laughter because you feel so...",
    clueZh: "嘴角上揚洋溢著滿滿的歡笑與喜悅心情真...",
    fitzgeraldCategory: 'adjectives',
    icon: "😊",
    order: 4,
    isFavorite: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-frustrated',
    categoryId: 'cat-feelings',
    label: "Frustrated",
    labelZh: "沮喪",
    spokenText: "I am feeling frustrated trying to express myself.",
    spokenTextZh: "我講不出來覺得有點沮喪。",
    definition: "Feeling annoyed or discouraged because things are not working as easily as expected.",
    definitionZh: "因事情不如預期順利或言語表達受阻而產生的沮喪鬱悶情緒。",
    exampleSentence: "When he had trouble finding the exact word he wanted, he took a deep breath to stay calm.",
    exampleSentenceZh: "當一時想不起想講的詞彙時，他先深呼吸一口氣讓自己放鬆。",
    phoneticSyllables: "Frus · trat · ed",
    clue: "When things are difficult and not going your way, you may feel...",
    clueZh: "事情不如預期讓人感到無奈與失落時很...",
    fitzgeraldCategory: 'adjectives',
    icon: "😣",
    order: 5,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-anxious',
    categoryId: 'cat-feelings',
    label: "Worried",
    labelZh: "擔心",
    spokenText: "I feel a bit worried.",
    spokenTextZh: "我心裡有點擔心。",
    definition: "Feeling unease, nervousness, or concern about an upcoming event or uncertainty.",
    definitionZh: "因對未知事物或即將發生的情況感到忐忑不安與掛念。",
    exampleSentence: "He felt a bit uneasy before the medical appointment, but his daughter held his hand.",
    exampleSentenceZh: "在前往醫院門診前他有些坐立難安，女兒握住他的手給予安撫。",
    phoneticSyllables: "Wor · ried",
    clue: "Feeling uneasy in your heart with anxious thoughts makes you...",
    clueZh: "心裡掛念著未完成的事情感到忐忑不安很...",
    fitzgeraldCategory: 'adjectives',
    icon: "😟",
    order: 6,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-tired',
    categoryId: 'cat-feelings',
    label: "Tired",
    labelZh: "很累",
    spokenText: "I am feeling tired.",
    spokenTextZh: "我感覺很累。",
    definition: "In need of rest or sleep due to physical or mental exertion.",
    definitionZh: "經過活動或思考後，體力與精神消耗、需要放鬆休息的狀態。",
    exampleSentence: "After completing his physical therapy routine, his eyelids grew heavy.",
    exampleSentenceZh: "完成了一整套肢體鍛鍊後，他感到眼皮沉重、只想坐下好好放鬆。",
    phoneticSyllables: "Tired",
    clue: "Yawning after a long busy day because you are feeling very...",
    clueZh: "忙碌了一整天眼皮沉重直打哈欠覺得...",
    fitzgeraldCategory: 'adjectives',
    icon: "🥱",
    order: 7,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-too-noisy',
    categoryId: 'cat-feelings',
    label: "Too Noisy",
    labelZh: "太吵了",
    spokenText: "It is too noisy here, can we quiet down?",
    spokenTextZh: "這裡太吵了，可以安靜一點嗎？",
    definition: "Experiencing excessive, unwanted, or overwhelming background sound volume.",
    definitionZh: "周遭環境聲音過大、刺耳或紛亂令人難以忍受。",
    exampleSentence: "The volume on the television was turned up high, so he covered his ears.",
    exampleSentenceZh: "電視播放的音量開得太大了，他忍不住伸手摀住耳朵。",
    phoneticSyllables: "Too · Noi · sy",
    clue: "Cover your ears from loud disruptive sounds because it is...",
    clueZh: "外面的喧嘩施工聲音震耳欲聾實在...",
    fitzgeraldCategory: 'adjectives',
    icon: "🙉",
    order: 8,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-repair-not-that',
    categoryId: 'cat-feelings',
    label: "Not What I Meant",
    labelZh: "不是這個意思",
    spokenText: "That is not what I meant. Let me try again.",
    spokenTextZh: "我不是那個意思，我再試一次。",
    definition: "A correction indicating that the listener has misunderstood your intention.",
    definitionZh: "用來糾正對方的理解、表明對方猜測或解讀錯誤的提示。",
    exampleSentence: "He signaled with his hands to let the caregiver know they had picked up the wrong item.",
    exampleSentenceZh: "他揮了揮手示意照護者拿錯了東西，剛才說的並不是那個物品。",
    phoneticSyllables: "Not · What · I · Meant",
    clue: "Clarifying a gentle misunderstanding by explaining that was...",
    clueZh: "您誤會我的表達想法了，其實...",
    fitzgeraldCategory: 'social',
    icon: "🙅‍♂️",
    order: 9,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-love',
    categoryId: 'cat-feelings',
    label: "I Love You",
    labelZh: "我愛你",
    spokenText: "I love you very much.",
    spokenTextZh: "我很愛你們。",
    definition: "A deep, affectionate bond and warm devotion felt toward family members.",
    definitionZh: "對親人與至愛之人深厚的關愛、依戀與溫暖情懷。",
    exampleSentence: "He held his wife's hand tenderly and smiled to express his gratitude and devotion.",
    exampleSentenceZh: "他溫柔地握住太太的手，用深情的眼神表達一生的珍惜與感激。",
    phoneticSyllables: "I · Love · You",
    clue: "Holding hands and expressing deep affection from the heart,...",
    clueZh: "握著親愛家人的雙手表達內心深深的情感...",
    fitzgeraldCategory: 'social',
    icon: "❤️",
    order: 10,
    isFavorite: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-quick-please',
    categoryId: 'cat-feelings',
    label: "Please",
    labelZh: "請",
    spokenText: "Please.",
    spokenTextZh: "請幫忙。",
    definition: "A polite word used to make a request courteous and respectful.",
    definitionZh: "提出要求時使用的禮貌用語，展現客氣與尊重。",
    exampleSentence: "He asked politely when requesting a glass of warm water from the kitchen.",
    exampleSentenceZh: "向身邊的人請託幫忙遞水杯時，他帶著微笑客氣地加上這句禮貌詞。",
    phoneticSyllables: "Please",
    clue: "A polite magic word to ask kindly for something is...",
    clueZh: "向他人尋求協助時最有禮貌的開頭詞是...",
    fitzgeraldCategory: 'social',
    icon: "🙏",
    order: 11,
    isFavorite: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-quick-thanks',
    categoryId: 'cat-feelings',
    label: "Thank You",
    labelZh: "謝謝",
    spokenText: "Thank you very much.",
    spokenTextZh: "謝謝你。",
    definition: "An expression of gratitude used to show appreciation for kindness or assistance.",
    definitionZh: "對他人提供的幫助、善意或關懷表達由衷感激的感謝詞。",
    exampleSentence: "When his daughter brought him a warm blanket, he gave a heartfelt smile of gratitude.",
    exampleSentenceZh: "當女兒為他送來暖和的蓋毯時，他雙手合十並露出由衷感激的微笑。",
    phoneticSyllables: "Thank · You",
    clue: "Show appreciation with gratitude for someone kindness by saying...",
    clueZh: "受到他人溫暖照顧心懷感激真誠致意說聲...",
    fitzgeraldCategory: 'social',
    icon: "💐",
    order: 12,
    isFavorite: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  // --- Family ---
  {
    id: 'card-family-daughter',
    categoryId: 'cat-family',
    label: "Daughter",
    labelZh: "女兒",
    spokenText: "Where is my daughter?",
    spokenTextZh: "我女兒在哪裡？",
    definition: "A female child in relation to her parents.",
    definitionZh: "父母親所生育撫養的女性孩子。",
    exampleSentence: "His female child visited on the weekend to help cook nutritious soup.",
    exampleSentenceZh: "他的掌上明珠在週末回來看望他，並在廚房熬煮營養熱湯。",
    phoneticSyllables: "Daugh · ter",
    clue: "Your sweet female child who grew up in your home is your...",
    clueZh: "家中乖巧貼心、如掌上明珠般的女性孩子是...",
    fitzgeraldCategory: 'people',
    icon: "👧",
    order: 1,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-family-son',
    categoryId: 'cat-family',
    label: "Son",
    labelZh: "兒子",
    spokenText: "Where is my son?",
    spokenTextZh: "我兒子在哪裡？",
    definition: "A male child in relation to his parents.",
    definitionZh: "父母親所生育撫養的男性孩子。",
    exampleSentence: "His male child called on the phone after work to ask how his rehabilitation went.",
    exampleSentenceZh: "下班後打電話回家關心爸爸今天復健進展的成年男性孩子。",
    phoneticSyllables: "Son",
    clue: "Your male child who shares your family name is your...",
    clueZh: "家中英俊挺拔、孝順懂事的男性孩子是...",
    fitzgeraldCategory: 'people',
    icon: "👦",
    order: 2,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-family-spouse',
    categoryId: 'cat-family',
    label: "Wife",
    labelZh: "太太",
    spokenText: "Where is my wife?",
    spokenTextZh: "我太太在哪裡？",
    definition: "A person's life partner in marriage.",
    definitionZh: "結為連理、攜手共度一生的人生伴侶。",
    exampleSentence: "His beloved lifelong companion sat beside him on the sofa holding his hand.",
    exampleSentenceZh: "結縭數十年的親密伴侶坐在他身旁，溫柔握著他的手一起看電視。",
    phoneticSyllables: "Wife",
    clue: "Your lifelong marriage partner and companion is your beloved...",
    clueZh: "攜手相伴一生、溫柔體貼的結髮牽手是...",
    fitzgeraldCategory: 'people',
    icon: "👵",
    order: 3,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-family-daughter-in-law',
    categoryId: 'cat-family',
    label: "Daughter-In-Law",
    labelZh: "媳婦",
    spokenText: "Where is my daughter-in-law?",
    spokenTextZh: "我媳婦在哪裡？",
    definition: "The spouse of one's son.",
    definitionZh: "兒子的合法配偶，家庭中的重要女性晚輩成員。",
    exampleSentence: "His son's wife prepared a delicious warm bowl of noodles for lunch.",
    exampleSentenceZh: "兒子的賢內助中午親自下廚煮了一碗香濃好入口的營養湯麵。",
    phoneticSyllables: "Daugh · ter · In · Law",
    clue: "The lovely woman married to your boy is your...",
    clueZh: "與家中男孩結為連理、賢慧孝順的配偶是...",
    fitzgeraldCategory: 'people',
    icon: "👩",
    order: 4,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-family-son-in-law',
    categoryId: 'cat-family',
    label: "Son-In-Law",
    labelZh: "女婿",
    spokenText: "Where is my son-in-law?",
    spokenTextZh: "我女婿在哪裡？",
    definition: "The spouse of one's daughter.",
    definitionZh: "女兒的合法配偶，家庭中的重要男性晚輩成員。",
    exampleSentence: "His daughter's husband fixed the kitchen cabinet handle over the weekend.",
    exampleSentenceZh: "女兒的丈夫在週末熱心前來幫忙修理客廳門窗與電器。",
    phoneticSyllables: "Son · In · Law",
    clue: "The fine gentleman married to your girl is your...",
    clueZh: "迎娶家中乖巧姑娘、可靠熱心的半子是...",
    fitzgeraldCategory: 'people',
    icon: "👨",
    order: 5,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-family-grandkids',
    categoryId: 'cat-family',
    label: "Grandchildren",
    labelZh: "孫子孫女",
    spokenText: "How are the grandkids doing?",
    spokenTextZh: "孫子孫女們好嗎？",
    definition: "The children of one's sons or daughters.",
    definitionZh: "兒女所生育的下一代年輕後輩，為家庭增添無數歡笑。",
    exampleSentence: "The young children of his son ran into the house giggling with hugs.",
    exampleSentenceZh: "兒女帶回家的活潑小娃兒們蹦蹦跳跳跑進客廳給長輩一個大擁抱。",
    phoneticSyllables: "Grand · chil · dren",
    clue: "The playful young offspring of your own kids are your adorable...",
    clueZh: "下一代活潑可愛、圍在膝旁撒嬌的小寶貝們是...",
    fitzgeraldCategory: 'people',
    icon: "👶",
    order: 6,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-family-dog',
    categoryId: 'cat-family',
    label: "Dog",
    labelZh: "狗狗",
    spokenText: "Where is the dog?",
    spokenTextZh: "狗狗在哪裡？",
    definition: "A four-legged domestic canine pet and loyal family companion.",
    definitionZh: "忠誠的四足毛茸茸寵物，是家庭裡忠實守護大家的好夥伴。",
    exampleSentence: "The furry family pet wagged its tail happily while resting by his slippers.",
    exampleSentenceZh: "毛茸茸的毛小孩搖著尾巴趴在他的拖鞋旁，安靜陪伴著主人。",
    phoneticSyllables: "Dog",
    clue: "Our four-legged loyal golden pet who wags her tail is our friendly...",
    clueZh: "毛茸茸四條腿搖著尾巴迎上來的小黃金獵犬是...",
    fitzgeraldCategory: 'nouns',
    icon: "🐶",
    order: 7,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  // --- Activities ---
  {
    id: 'card-tv',
    categoryId: 'cat-activities',
    label: "Watch TV",
    labelZh: "看電視",
    spokenText: "Can we turn on the TV or watch a show?",
    spokenTextZh: "我想看電視。",
    definition: "An electronic device with a screen that broadcasts news, movies, and shows.",
    definitionZh: "播放新聞、電影與各類影音節目的客廳大螢幕視聽家電。",
    exampleSentence: "He relaxed on the couch while watching the evening news broadcast on the screen.",
    exampleSentenceZh: "晚飯後他坐在沙發上放鬆，收看大螢幕上播放的七點晚間新聞。",
    phoneticSyllables: "Watch · T · V",
    clue: "Turn on the living room screen with the remote to...",
    clueZh: "拿著遙控器打開客廳螢幕觀賞精采節目...",
    fitzgeraldCategory: 'verbs',
    icon: "📺",
    order: 1,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-music',
    categoryId: 'cat-activities',
    label: "Music",
    labelZh: "聽音樂",
    spokenText: "I would like to listen to some music.",
    spokenTextZh: "我想聽音樂。",
    definition: "Vocal or instrumental sounds combined to produce beauty of form and emotion.",
    definitionZh: "由樂器演奏或歌聲組成的悅耳旋律，能撫慰心靈與陶冶性情。",
    exampleSentence: "Soft classical melodies played gently through the speaker to create a calm room.",
    exampleSentenceZh: "音響中流淌出悠揚古典的弦樂旋律，讓整個房間充滿寧靜氛圍。",
    phoneticSyllables: "Mu · sic",
    clue: "Put on headphones to enjoy melodious songs and beautiful...",
    clueZh: "戴上耳機聆聽優美動人的旋律與...",
    fitzgeraldCategory: 'nouns',
    icon: "🎵",
    order: 2,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-walk',
    categoryId: 'cat-activities',
    label: "Go for a Walk",
    labelZh: "去散步",
    spokenText: "Can we go outside for some fresh air or a walk?",
    spokenTextZh: "我想出去走走散步。",
    definition: "Moving along on foot at a steady, leisurely pace for exercise or recreation.",
    definitionZh: "以悠閒舒適的步調邁開雙腿慢行，有助於活動筋骨與呼吸新鮮空氣。",
    exampleSentence: "He put on his walking shoes and strolled gently down the garden path with his caregiver.",
    exampleSentenceZh: "他穿上輕便健走鞋，在照護者陪伴下到社區花園步道漫步活動。",
    phoneticSyllables: "Go · for · a · walk",
    clue: "Put on comfortable walking shoes and step outside to...",
    clueZh: "穿上好走的慢跑鞋到附近的公園綠地...",
    fitzgeraldCategory: 'verbs',
    icon: "🚶",
    order: 3,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-video-call',
    categoryId: 'cat-activities',
    label: "Video Call",
    labelZh: "視訊電話",
    spokenText: "I would like to make a video call with family.",
    spokenTextZh: "我想和家人打視訊電話。",
    definition: "A digital phone call where participants can see each other in real time on screens.",
    definitionZh: "透過智慧手機或平板螢幕，讓相隔兩地的人即時面對面通話的科技。",
    exampleSentence: "He held the tablet up to see his daughter's smiling face while she was at college.",
    exampleSentenceZh: "他拿起平板電腦，在螢幕上即時看見遠在外地上學的女兒親切笑臉。",
    phoneticSyllables: "Vid · e · o · Call",
    clue: "Look into the tablet camera to chat face-to-face on a...",
    clueZh: "打開平板螢幕與遠方親友即時連線聊天的...",
    fitzgeraldCategory: 'verbs',
    icon: "📱",
    order: 4,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-sunshine',
    categoryId: 'cat-activities',
    label: "Enjoy Sunshine",
    labelZh: "曬太陽",
    spokenText: "I would like to sit by the window and enjoy some sunshine.",
    spokenTextZh: "我想在窗邊曬曬太陽、看看外面。",
    definition: "The natural direct light and warmth produced by the sun.",
    definitionZh: "太陽所散發出的天然光線與溫暖熱度，有助於生成維生素D。",
    exampleSentence: "He sat in the courtyard chair to absorb the natural gentle warmth on his shoulders.",
    exampleSentenceZh: "他坐在庭院的休閒椅上，感受天然金色陽光灑在肩膀上的溫煦暖意。",
    phoneticSyllables: "Sun · shine",
    clue: "Sit on the open patio soaking in warm natural rays to...",
    clueZh: "坐在戶外陽台沐浴在暖洋洋的金色光芒下...",
    fitzgeraldCategory: 'verbs',
    icon: "☀️",
    order: 5,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-therapy-action',
    categoryId: 'cat-activities',
    label: "Speech Practice",
    labelZh: "語言復健",
    spokenText: "Let us do our speech therapy exercises.",
    spokenTextZh: "我們來做語言復健練習。",
    definition: "Structured vocal, language, or physical exercises guided by a clinician to restore skills.",
    definitionZh: "在專業人員指導下進行的發音、找字或肢體功能恢復訓練。",
    exampleSentence: "He practiced articulating clear syllables with his specialist for thirty minutes.",
    exampleSentenceZh: "他在專業復健師的指導下，專注練習發音與找字達三十分鐘。",
    phoneticSyllables: "Speech · Prac · tice",
    clue: "Work on flashcards with your therapist to complete your daily...",
    clueZh: "跟著治療師一起練習字詞發音的專業...",
    fitzgeraldCategory: 'verbs',
    icon: "🗣️",
    order: 6,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-gardening',
    categoryId: 'cat-activities',
    label: "Gardening",
    labelZh: "整理花草",
    spokenText: "I would like to do some gardening.",
    spokenTextZh: "我想去整理花草、澆澆花。",
    definition: "Tending, watering, and cultivating plants, flowers, and greenery in a yard.",
    definitionZh: "修剪花草、澆灌盆栽與培育綠色植物的戶外怡情活動。",
    exampleSentence: "He used a watering can to nourish the blooming red roses on the balcony.",
    exampleSentenceZh: "他拿著綠色小水壺，細心為陽台上盛開的花草植物澆水灌溉。",
    phoneticSyllables: "Gar · den · ing",
    clue: "Water the potted green plants and prune flowers for fun...",
    clueZh: "拿著小水壺在庭院澆水修剪盆栽的休閒是...",
    fitzgeraldCategory: 'verbs',
    icon: "🌱",
    order: 7,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-wash-dishes',
    categoryId: 'cat-activities',
    label: "Wash Dishes",
    labelZh: "洗碗",
    spokenText: "I want to wash the dishes.",
    spokenTextZh: "我想洗碗。",
    definition: "Cleaning plates, bowls, cups, and utensils after a meal using soap and water.",
    definitionZh: "用餐後使用清潔劑與清水將碗盤、筷子與鍋具洗滌乾淨。",
    exampleSentence: "He helped rinse the ceramic bowls with warm water at the kitchen sink.",
    exampleSentenceZh: "他在廚房流理台前用溫水與海綿將用過的陶瓷餐具沖洗得乾乾淨淨。",
    phoneticSyllables: "Wash · Dish · es",
    clue: "Scrub the plates, cups, and forks in the sink with soap to...",
    clueZh: "用餐完畢後在流理台用清潔劑刷洗乾淨餐盤...",
    fitzgeraldCategory: 'verbs',
    icon: "🧼",
    order: 8,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-exercise',
    categoryId: 'cat-activities',
    label: "Exercise",
    labelZh: "做運動",
    spokenText: "Let us do some physical exercise and stretching.",
    spokenTextZh: "我們一起來做運動伸展。",
    definition: "Engaging in physical exertion to improve strength, flexibility, and mobility.",
    definitionZh: "進行體能活動以增強肌肉力量、柔軟度與血液循環。",
    exampleSentence: "He raised his arms gently above his head and stretched his legs with resistance bands.",
    exampleSentenceZh: "他握著彈力帶緩緩抬起手臂並伸展雙腿，鍛鍊肌力與關節活動度。",
    phoneticSyllables: "Ex · er · cise",
    clue: "Stretch your arms and legs to stay active and...",
    clueZh: "動動筋骨舒展四肢保持健康的體適能...",
    fitzgeraldCategory: 'verbs',
    icon: "💪",
    order: 9,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  // --- Places ---
  {
    id: 'card-home',
    categoryId: 'cat-places',
    label: "Home",
    labelZh: "回家",
    spokenText: "I want to be at home.",
    spokenTextZh: "我想在家裡。",
    definition: "The comfortable residence where a person lives and feels safe with family.",
    definitionZh: "自己與家人長期居住、最具安全感與歸屬感的溫馨住所。",
    exampleSentence: "After a long day out, he stepped through his own front door with a sigh of relief.",
    exampleSentenceZh: "出門一整天後推開熟悉的大門，回到充滿溫暖回憶的熟悉住處。",
    phoneticSyllables: "Home",
    clue: "Return to your cozy residence where family lives to go back...",
    clueZh: "結束外出行程回到溫暖舒適的住所...",
    fitzgeraldCategory: 'places',
    icon: "🏠",
    order: 1,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-bedroom',
    categoryId: 'cat-places',
    label: "Bedroom",
    labelZh: "房間",
    spokenText: "Can we go to the bedroom?",
    spokenTextZh: "我們去房間。",
    definition: "A private room in a house furnished with a bed used primarily for sleeping.",
    definitionZh: "屋內擺設大床、衣櫃與床頭櫃，主要供人睡眠休息的私密房間。",
    exampleSentence: "He walked down the quiet hallway and closed the door of his sleeping quarters.",
    exampleSentenceZh: "他走過走廊回到自己擺放著柔軟大床的房間，準備安靜歇息。",
    phoneticSyllables: "Bed · room",
    clue: "The private living space with your comfy bed and dresser is your...",
    clueZh: "擺放著大床與衣櫃、供個人專屬休憩的專屬...",
    fitzgeraldCategory: 'places',
    icon: "🛏️",
    order: 2,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-outside',
    categoryId: 'cat-places',
    label: "Outside",
    labelZh: "去戶外",
    spokenText: "I would like to go outside.",
    spokenTextZh: "我想去戶外走走。",
    definition: "The open-air environment outside of buildings, surrounded by nature.",
    definitionZh: "建築物之外、綠意盎然且空氣清新的大自然露天環境。",
    exampleSentence: "He opened the sliding door to breathe the fresh breeze among the trees and grass.",
    exampleSentenceZh: "他推開落地窗走到庭院草地上，大口呼吸微風拂過的清新空氣。",
    phoneticSyllables: "Out · side",
    clue: "Open the front door and step into the fresh open air to go...",
    clueZh: "推開大門走出室內感受大自然新鮮空氣...",
    fitzgeraldCategory: 'places',
    icon: "🌳",
    order: 3,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-hospital',
    categoryId: 'cat-places',
    label: "Hospital",
    labelZh: "醫院",
    spokenText: "We need to go to the hospital.",
    spokenTextZh: "我們需要去醫院。",
    definition: "A major medical facility providing comprehensive healthcare, diagnosis, and treatment.",
    definitionZh: "設有各專科門診、住院病房與先進儀器的綜合大型醫療照護機構。",
    exampleSentence: "The transport van arrived at the main medical building for his annual checkup.",
    exampleSentenceZh: "交通接駁車抵達了設有先進設備的醫療大樓，準備進行常規檢查。",
    phoneticSyllables: "Hos · pi · tal",
    clue: "The large medical facility with inpatient wards and emergency care is the...",
    clueZh: "設有大型急診室與各科病房的綜合大型...",
    fitzgeraldCategory: 'places',
    icon: "🏥",
    order: 4,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-clinic',
    categoryId: 'cat-places',
    label: "Clinic",
    labelZh: "診所",
    spokenText: "We need to go to the clinic for therapy.",
    spokenTextZh: "我們去診所看診復健。",
    definition: "A local medical establishment smaller than a hospital, providing outpatient care.",
    definitionZh: "設立於社區周邊、提供門診諮詢與基層醫療服務的醫療所。",
    exampleSentence: "He walked over to the neighborhood healthcare center to have his prescription refilled.",
    exampleSentenceZh: "他走到社區巷口的醫療診所，由熟識的家庭醫師為他調配處方籤。",
    phoneticSyllables: "Clin · ic",
    clue: "A local neighborhood outpatient health office for regular checkups is a...",
    clueZh: "社區巷口方便看感冒與拿藥的基層小型...",
    fitzgeraldCategory: 'places',
    icon: "🩺",
    order: 5,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-car',
    categoryId: 'cat-places',
    label: "Car Ride",
    labelZh: "搭車兜風",
    spokenText: "I would like to go for a drive.",
    spokenTextZh: "我想搭車出去兜風。",
    definition: "A four-wheeled motorized vehicle used for transportation on roads.",
    definitionZh: "具備四個輪子、行駛於道路上的代步交通工具。",
    exampleSentence: "He buckled his seatbelt in the passenger seat for a smooth trip around the lake.",
    exampleSentenceZh: "他坐進副駕駛座繫好安全帶，享受一趟沿著湖畔欣賞風景的公路旅程。",
    phoneticSyllables: "Car",
    clue: "Fasten your seatbelt inside the passenger vehicle for a scenic...",
    clueZh: "繫好安全帶坐在副駕駛座欣賞沿途風景的...",
    fitzgeraldCategory: 'places',
    icon: "🚗",
    order: 6,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  // --- Date & Time ---
  {
    id: 'card-time-today',
    categoryId: 'cat-time',
    label: "Today",
    labelZh: "今天",
    spokenText: "Today.",
    spokenTextZh: "今天。",
    definition: "The present day in real time; the current 24-hour period.",
    definitionZh: "當前正在度過的這個日子；此時此刻的這一天。",
    exampleSentence: "The calendar square marked with a red circle shows the present date.",
    exampleSentenceZh: "掛曆上用紅筆圈起來的日期，代表我們此時此刻度過的這一天。",
    phoneticSyllables: "To · day",
    clue: "The present 24-hour day occurring right now on the calendar is...",
    clueZh: "日曆上正值當下、我們正在度過的這一天是...",
    fitzgeraldCategory: 'nouns',
    icon: "📅",
    order: 1,
    isFavorite: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-time-tomorrow',
    categoryId: 'cat-time',
    label: "Tomorrow",
    labelZh: "明天",
    spokenText: "Tomorrow.",
    spokenTextZh: "明天。",
    definition: "The day following immediately after today.",
    definitionZh: "緊接在今天之後的那一天；即將到來的新日子。",
    exampleSentence: "We scheduled the routine dental checkup for the following morning after tonight.",
    exampleSentenceZh: "我們把牙齒常規檢查預約在今晚過後的下一個早晨。",
    phoneticSyllables: "To · mor · row",
    clue: "The upcoming day right after tonight when the sun rises next is...",
    clueZh: "今晚就寢天亮之後、即將迎來的嶄新一天是...",
    fitzgeraldCategory: 'nouns',
    icon: "⏩",
    order: 2,
    isFavorite: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-time-yesterday',
    categoryId: 'cat-time',
    label: "Yesterday",
    labelZh: "昨天",
    spokenText: "Yesterday.",
    spokenTextZh: "昨天。",
    definition: "The day preceding today; the previous 24-hour period.",
    definitionZh: "緊接在今天之前已經過去的那一天；前一天。",
    exampleSentence: "He reminisced about the pleasant walk he took twenty-four hours ago.",
    exampleSentenceZh: "他回憶起前一天下午在社區公園散步時看見的盛開花木。",
    phoneticSyllables: "Yes · ter · day",
    clue: "The previous day that ended when you went to bed last night was...",
    clueZh: "已經過去結束的上一天、昨晚之前的日子是...",
    fitzgeraldCategory: 'nouns',
    icon: "⏪",
    order: 3,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-time-now',
    categoryId: 'cat-time',
    label: "Now",
    labelZh: "現在",
    spokenText: "Right now, please.",
    spokenTextZh: "現在。",
    definition: "At the present moment; without any delay.",
    definitionZh: "此時此刻；當下的瞬間，不作任何拖延。",
    exampleSentence: "He looked at his watch and said it was the exact moment to depart.",
    exampleSentenceZh: "他看了看手錶上的指針，表示正是出發的精準時刻。",
    phoneticSyllables: "Now",
    clue: "At this exact current instant without any delay, we do it...",
    clueZh: "就在此時此刻、分秒不差的當下就是...",
    fitzgeraldCategory: 'adjectives',
    icon: "⏱️",
    order: 4,
    isFavorite: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-time-later',
    categoryId: 'cat-time',
    label: "Later",
    labelZh: "等一下",
    spokenText: "Later, please.",
    spokenTextZh: "等一下。",
    definition: "At a subsequent time in the future; after an interval.",
    definitionZh: "在未來的某個時間點；經過一段時間之後。",
    exampleSentence: "He finished his lunch first and planned to read his magazine in an hour.",
    exampleSentenceZh: "他先專心吃完午餐，打算過一個小時後再來翻閱雜誌。",
    phoneticSyllables: "La · ter",
    clue: "Not right at this second, but in a short while afterwards, we do it...",
    clueZh: "先稍安勿躁不用急、待會過些時候再處理請...",
    fitzgeraldCategory: 'adjectives',
    icon: "⏳",
    order: 5,
    isFavorite: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-time-morning',
    categoryId: 'cat-time',
    label: "Morning",
    labelZh: "早上",
    spokenText: "In the morning.",
    spokenTextZh: "早上。",
    definition: "The early part of the day between dawn and noon.",
    definitionZh: "從黎明日出到正午十二點之間的這段清晨至上午時光。",
    exampleSentence: "Birds chirped outside his bedroom window as the early sunshine broke through.",
    exampleSentenceZh: "窗外鳥兒清脆啼叫，清晨的金色陽光穿透薄霧照亮大地。",
    phoneticSyllables: "Morn · ing",
    clue: "The early dawn hours after sunrise when we eat breakfast is the...",
    clueZh: "太陽初升、剛起床享用熱騰騰早點的時段是...",
    fitzgeraldCategory: 'nouns',
    icon: "🌅",
    order: 6,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-time-afternoon',
    categoryId: 'cat-time',
    label: "Afternoon",
    labelZh: "下午",
    spokenText: "In the afternoon.",
    spokenTextZh: "下午。",
    definition: "The part of the day between noon and evening.",
    definitionZh: "從正午十二點過後至太陽西下傍晚之間的午後時光。",
    exampleSentence: "He enjoyed a slice of fruit and a warm beverage around three o'clock.",
    exampleSentenceZh: "午後三點左右，他享用了一小盤切片水果配溫茶點心。",
    phoneticSyllables: "Af · ter · noon",
    clue: "The daytime hours between lunch and dusk when we have tea is the...",
    clueZh: "午飯過後到黃昏天黑前悠閒散步喝茶的時段是...",
    fitzgeraldCategory: 'nouns',
    icon: "🌤️",
    order: 7,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-time-night',
    categoryId: 'cat-time',
    label: "Night",
    labelZh: "晚上",
    spokenText: "Tonight or at night.",
    spokenTextZh: "晚上。",
    definition: "The period of ambient darkness between sunset and sunrise.",
    definitionZh: "太陽落山後直到隔天黎明之間、星月升起的黑暗時段。",
    exampleSentence: "The stars sparkled in the dark sky as the family prepared for bed.",
    exampleSentenceZh: "夜空中繁星閃爍，全家人在寧靜的夜色中準備安寢。",
    phoneticSyllables: "Night",
    clue: "The dark hours when the moon shines and we go to sleep is the...",
    clueZh: "月亮高掛星空閃爍、準備熄燈安睡的時段是...",
    fitzgeraldCategory: 'nouns',
    icon: "🌙",
    order: 8,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-day-mon',
    categoryId: 'cat-time',
    label: "Monday",
    labelZh: "星期一",
    spokenText: "Monday.",
    spokenTextZh: "星期一。",
    definition: "The first day of the standard working week, following Sunday.",
    definitionZh: "一般工作週的第一天，緊接在週日之後。",
    exampleSentence: "He started the new week with a fresh rehabilitation schedule on the calendar.",
    exampleSentenceZh: "每週伊始，他在每週最初的一天精神飽滿地展開新復健計畫。",
    phoneticSyllables: "Mon · day",
    clue: "The first weekday right after the weekend concludes is...",
    clueZh: "週末假期結束後、開啟每週工作日的第一天是...",
    fitzgeraldCategory: 'nouns',
    icon: "🗓️",
    order: 9,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-day-tue',
    categoryId: 'cat-time',
    label: "Tuesday",
    labelZh: "星期二",
    spokenText: "Tuesday.",
    spokenTextZh: "星期二。",
    definition: "The second day of the standard working week, following Monday.",
    definitionZh: "一週當中的第二天，位於週一與週三之間。",
    exampleSentence: "The physical therapist arrives for the second home session of the week.",
    exampleSentenceZh: "復健師在一週的第二天準時按響門鈴進行到府評估。",
    phoneticSyllables: "Tues · day",
    clue: "The second weekday sitting right before Wednesday is...",
    clueZh: "一週工作日的第二天、排在週一之後的是...",
    fitzgeraldCategory: 'nouns',
    icon: "🗓️",
    order: 10,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-day-wed',
    categoryId: 'cat-time',
    label: "Wednesday",
    labelZh: "星期三",
    spokenText: "Wednesday.",
    spokenTextZh: "星期三。",
    definition: "The third day of the standard working week, marking the middle of the week.",
    definitionZh: "一週當中的第三天，通常標誌著週中樞紐。",
    exampleSentence: "Reaching the middle of the week, he enjoyed a special lunch with family.",
    exampleSentenceZh: "來到了一週的正中央這一天，他和家人一起享用了美味午餐。",
    phoneticSyllables: "Wednes · day",
    clue: "The middle hump day of the standard work week is...",
    clueZh: "一週五個工作天正中間的那一天是...",
    fitzgeraldCategory: 'nouns',
    icon: "🗓️",
    order: 11,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-day-thu',
    categoryId: 'cat-time',
    label: "Thursday",
    labelZh: "星期四",
    spokenText: "Thursday.",
    spokenTextZh: "星期四。",
    definition: "The fourth day of the standard working week, preceding Friday.",
    definitionZh: "一週當中的第四天，位於週三與週五之間。",
    exampleSentence: "He checked off his vocal goals on the fourth day of his exercise plan.",
    exampleSentenceZh: "在一週的第四天，他在日曆上打勾完成今天的發音練習。",
    phoneticSyllables: "Thurs · day",
    clue: "The fourth weekday situated just before Friday is...",
    clueZh: "排在週三之後、即將迎接週末前夕的是...",
    fitzgeraldCategory: 'nouns',
    icon: "🗓️",
    order: 12,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-day-fri',
    categoryId: 'cat-time',
    label: "Friday",
    labelZh: "星期五",
    spokenText: "Friday.",
    spokenTextZh: "星期五。",
    definition: "The fifth day of the working week, leading directly into the weekend.",
    definitionZh: "工作週的最後一個工作天，隨後即將進入週末假期。",
    exampleSentence: "Everyone was in high spirits anticipating the upcoming weekend gatherings.",
    exampleSentenceZh: "結束了這週最後一個工作日的功課，全家開心地期待週末團聚。",
    phoneticSyllables: "Fri · day",
    clue: "The celebratory final weekday before the weekend starts is...",
    clueZh: "五個工作日當中的最後一天、下班便迎向週末的是...",
    fitzgeraldCategory: 'nouns',
    icon: "🗓️",
    order: 13,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-day-sat',
    categoryId: 'cat-time',
    label: "Saturday",
    labelZh: "星期六",
    spokenText: "Saturday.",
    spokenTextZh: "星期六。",
    definition: "The first day of the weekend, a popular day for recreation and family visits.",
    definitionZh: "週末假期的第一天，常見於家庭聚會與出外踏青。",
    exampleSentence: "His grandchildren came over in the morning for a fun day of board games.",
    exampleSentenceZh: "在週末假期的第一天早晨，孫子孫女興高采烈地來家裡玩桌遊。",
    phoneticSyllables: "Sat · ur · day",
    clue: "The first weekend day for family outings and relaxation is...",
    clueZh: "每逢週末的第一個放假日、不用上班上學的是...",
    fitzgeraldCategory: 'nouns',
    icon: "🗓️",
    order: 14,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-day-sun',
    categoryId: 'cat-time',
    label: "Sunday",
    labelZh: "星期日",
    spokenText: "Sunday.",
    spokenTextZh: "星期日。",
    definition: "The closing day of the weekend, dedicated to rest before the new week begins.",
    definitionZh: "週末假期的第二天與收尾之日，適合靜養休息準備新的一週。",
    exampleSentence: "The family shared a calm afternoon tea and prepared for the week ahead.",
    exampleSentenceZh: "全家人在週末假期的最後一天共享悠閒下午茶，收心調養。",
    phoneticSyllables: "Sun · day",
    clue: "The peaceful second weekend day before a new week begins is...",
    clueZh: "每逢週末假期的最後一天、隔天即將開工的是...",
    fitzgeraldCategory: 'nouns',
    icon: "🗓️",
    order: 15,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-time-what-time',
    categoryId: 'cat-time',
    label: "What Time?",
    labelZh: "現在幾點？",
    spokenText: "What time is it?",
    spokenTextZh: "現在幾點了？",
    definition: "A question asking for the current hour and minute displayed on a clock.",
    definitionZh: "詢問當前鐘錶上所指精確時刻（幾點幾分）的問句。",
    exampleSentence: "He pointed to his wrist to ask how many minutes remained before lunch.",
    exampleSentenceZh: "他指了指手腕上的錶帶，詢問距離開飯還有多少分鐘。",
    phoneticSyllables: "What · Time",
    clue: "Looking at the clock dial to ask about the hour,...",
    clueZh: "抬頭看著牆上時鐘指針詢問時刻...",
    fitzgeraldCategory: 'social',
    icon: "🕐",
    order: 16,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-time-what-day',
    categoryId: 'cat-time',
    label: "What Day?",
    labelZh: "今天星期幾？",
    spokenText: "What day is it today?",
    spokenTextZh: "今天星期幾？",
    definition: "A question inquiring about which specific day of the week it is.",
    definitionZh: "詢問今天究竟是週一至週日哪一天的問句。",
    exampleSentence: "He checked the top banner on his tablet to confirm the weekday schedule.",
    exampleSentenceZh: "他看了看螢幕上方的星期欄位，確認今天對應的是一週中的哪一天。",
    phoneticSyllables: "What · Day",
    clue: "Looking at the weekly calendar to ask about the day,...",
    clueZh: "翻閱七天日曆確認每週進度詢問...",
    fitzgeraldCategory: 'social',
    icon: "📅",
    order: 17,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-time-next-week',
    categoryId: 'cat-time',
    label: "Next Week",
    labelZh: "下星期",
    spokenText: "Next week.",
    spokenTextZh: "下個星期。",
    definition: "The seven-day calendar block following immediately after the current one.",
    definitionZh: "緊接在當前這七天之後的下一個整週週期。",
    exampleSentence: "The speech pathologist booked their follow-up evaluation for the coming cycle.",
    exampleSentenceZh: "專業語言治療師將下一次的深入評估預約在下一個七天週期。",
    phoneticSyllables: "Next · Week",
    clue: "The upcoming seven-day calendar block arriving after this one is...",
    clueZh: "日曆上排在當前這七天之後、即將到來的下一個整週是...",
    fitzgeraldCategory: 'nouns',
    icon: "⏩",
    order: 18,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-time-last-week',
    categoryId: 'cat-time',
    label: "Last Week",
    labelZh: "上星期",
    spokenText: "Last week.",
    spokenTextZh: "上個星期。",
    definition: "The seven-day calendar period preceding the current one.",
    definitionZh: "緊接在當前這七天之前、已經結束的前一個整週週期。",
    exampleSentence: "He proudly remembered the therapy milestones he had achieved seven days ago.",
    exampleSentenceZh: "他高興地回想七天前那段時間自己在肢體活動上所達成的進步。",
    phoneticSyllables: "Last · Week",
    clue: "The past seven-day calendar block that has already finished was...",
    clueZh: "日曆上排在當前這週之前、已經過去結束的前一個整週是...",
    fitzgeraldCategory: 'nouns',
    icon: "⏪",
    order: 19,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  // --- Numbers ---
  {
    id: 'card-num-0',
    categoryId: 'cat-numbers',
    label: "Zero",
    labelZh: "零",
    spokenText: "Zero.",
    spokenTextZh: "零。",
    definition: "The numerical digit representing the absence of all quantity; zero.",
    definitionZh: "代表沒有任何數量、空無一物的數字基底「零」。",
    exampleSentence: "There were no crumbs remaining on the empty dessert plate.",
    exampleSentenceZh: "吃得乾乾淨淨的點心盤子上沒有留下任何一點碎屑。",
    phoneticSyllables: "Ze · ro",
    clue: "The round circular numeral meaning nothing at all is...",
    clueZh: "代表完全沒有任何數量、圓圈形狀的數字是...",
    fitzgeraldCategory: 'adjectives',
    icon: "0️⃣",
    order: 1,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-num-1',
    categoryId: 'cat-numbers',
    label: "One",
    labelZh: "一",
    spokenText: "One.",
    spokenTextZh: "一。",
    definition: "The single whole unit; the first positive integer.",
    definitionZh: "代表單一、第一位正整數的基礎數字單位「一」。",
    exampleSentence: "He held up a single index finger to request a single serving of tea.",
    exampleSentenceZh: "他豎起一根食指，示意只需要添上一杯清香好茶。",
    phoneticSyllables: "One",
    clue: "The single first numeral when starting to count is...",
    clueZh: "數數時排在最前面、代表首位個體的數字是...",
    fitzgeraldCategory: 'adjectives',
    icon: "1️⃣",
    order: 2,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-num-2',
    categoryId: 'cat-numbers',
    label: "Two",
    labelZh: "二",
    spokenText: "Two.",
    spokenTextZh: "二。",
    definition: "The numerical value equal to one plus one; a pair.",
    definitionZh: "一加一相等的數量；代表一雙或一對的數字「二」。",
    exampleSentence: "He placed two soft pillows behind his back for support.",
    exampleSentenceZh: "他在身後放了兩個柔軟的靠墊來支撐腰部。",
    phoneticSyllables: "Two",
    clue: "The numeral for a pair of shoes or both eyes is...",
    clueZh: "代表成雙成對、一雙鞋子或雙眼的數字是...",
    fitzgeraldCategory: 'adjectives',
    icon: "2️⃣",
    order: 3,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-num-3',
    categoryId: 'cat-numbers',
    label: "Three",
    labelZh: "三",
    spokenText: "Three.",
    spokenTextZh: "三。",
    definition: "The integer equal to two plus one; a trio.",
    definitionZh: "代表二加一的整數數量；三人或三樣物品的計數。",
    exampleSentence: "The recipe called for three ripe red apples sliced into quarters.",
    exampleSentenceZh: "料理盤中擺放了三顆洗淨切片的香甜紅蘋果。",
    phoneticSyllables: "Three",
    clue: "The numeral for the points of a triangle is...",
    clueZh: "交通錐側面輪廓頂點數量、排在二後面的數字是...",
    fitzgeraldCategory: 'adjectives',
    icon: "3️⃣",
    order: 4,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-num-4',
    categoryId: 'cat-numbers',
    label: "Four",
    labelZh: "四",
    spokenText: "Four.",
    spokenTextZh: "四。",
    definition: "The integer equal to three plus one; the number of corners on a square.",
    definitionZh: "代表三加一的整數；正方形四個頂角與輪胎的計數。",
    exampleSentence: "A standard dining chair has four sturdy wooden legs.",
    exampleSentenceZh: "客廳裡的實木餐椅下方有四根穩固的支撐椅腳。",
    phoneticSyllables: "Four",
    clue: "The numeral for the wheels on a standard sedan is...",
    clueZh: "轎車全部輪胎或是正方形全部頂角的數量是...",
    fitzgeraldCategory: 'adjectives',
    icon: "4️⃣",
    order: 5,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-num-5',
    categoryId: 'cat-numbers',
    label: "Five",
    labelZh: "五",
    spokenText: "Five.",
    spokenTextZh: "五。",
    definition: "The integer equal to four plus one; the count of digits on one human hand.",
    definitionZh: "代表四加一的整數；一隻手掌上的五根手指數量。",
    exampleSentence: "He spread his fingers wide to show all five digits in a high-five.",
    exampleSentenceZh: "他張開手掌露出全部手指，與身邊的親人擊掌慶祝。",
    phoneticSyllables: "Five",
    clue: "The count of fingers on a single palm is...",
    clueZh: "我們單一隻手掌上擁有的手指頭總數是...",
    fitzgeraldCategory: 'adjectives',
    icon: "5️⃣",
    order: 6,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-num-6',
    categoryId: 'cat-numbers',
    label: "Six",
    labelZh: "六",
    spokenText: "Six.",
    spokenTextZh: "六。",
    definition: "The integer equal to five plus one; a half dozen.",
    definitionZh: "代表五加一的整數；半打的計量單位。",
    exampleSentence: "The carton contained six fresh brown eggs for baking.",
    exampleSentenceZh: "紙盒中裝有半打新鮮洗選雞蛋，準備烹調早餐。",
    phoneticSyllables: "Six",
    clue: "The count of faces on a playing cube or half a dozen is...",
    clueZh: "一顆正方體骰子全部的面數、等於半打的數字是...",
    fitzgeraldCategory: 'adjectives',
    icon: "6️⃣",
    order: 7,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-num-7',
    categoryId: 'cat-numbers',
    label: "Seven",
    labelZh: "七",
    spokenText: "Seven.",
    spokenTextZh: "七。",
    definition: "The integer equal to six plus one; the number of days in a full week.",
    definitionZh: "代表六加一的整數；一整週七天循環的總天數。",
    exampleSentence: "There are seven distinct days in a complete calendar week.",
    exampleSentenceZh: "在一個完整的日曆週當中，包含著整整七天時光。",
    phoneticSyllables: "Sev · en",
    clue: "The total count of days in one whole week is...",
    clueZh: "從星期一數到星期日、一整週的總天數是...",
    fitzgeraldCategory: 'adjectives',
    icon: "7️⃣",
    order: 8,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-num-8',
    categoryId: 'cat-numbers',
    label: "Eight",
    labelZh: "八",
    spokenText: "Eight.",
    spokenTextZh: "八。",
    definition: "The integer equal to seven plus one; the count of legs on an octopus.",
    definitionZh: "代表七加一的整數；章魚爪的數量。",
    exampleSentence: "He slept soundly for eight restful hours overnight.",
    exampleSentenceZh: "他昨晚安穩睡足了整整八個小時，精神極為充沛。",
    phoneticSyllables: "Eight",
    clue: "The count of tentacles on an octopus shaped like stacked circles is...",
    clueZh: "章魚全部觸手的數量、形狀像兩個圓圈疊在一起的數字是...",
    fitzgeraldCategory: 'adjectives',
    icon: "8️⃣",
    order: 9,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-num-9',
    categoryId: 'cat-numbers',
    label: "Nine",
    labelZh: "九",
    spokenText: "Nine.",
    spokenTextZh: "九。",
    definition: "The integer equal to eight plus one; the highest single decimal digit.",
    definitionZh: "代表八加一的整數；十進位制中最大的個位數。",
    exampleSentence: "The baseball game concluded after nine complete innings.",
    exampleSentenceZh: "棒球比賽在雙方打滿九局後圓滿分出勝負。",
    phoneticSyllables: "Nine",
    clue: "The largest single digit in base ten right before ten is...",
    clueZh: "個位數中最大的數、緊接在十前面的數字是...",
    fitzgeraldCategory: 'adjectives',
    icon: "9️⃣",
    order: 10,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-num-10',
    categoryId: 'cat-numbers',
    label: "Ten",
    labelZh: "十",
    spokenText: "Ten.",
    spokenTextZh: "十。",
    definition: "The base number of the decimal system; the count of fingers on two hands.",
    definitionZh: "十進位制的基數；雙手手掌全部十根手指的總和。",
    exampleSentence: "He held up both open hands to display all ten fingers proudly.",
    exampleSentenceZh: "他高高舉起雙手手掌，開心地展示雙手全部的手指。",
    phoneticSyllables: "Ten",
    clue: "The total count of fingers on both of your hands is...",
    clueZh: "雙手手掌手指頭全部加總起來的二位數起點是...",
    fitzgeraldCategory: 'adjectives',
    icon: "🔟",
    order: 11,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-num-11',
    categoryId: 'cat-numbers',
    label: "Eleven",
    labelZh: "十一",
    spokenText: "Eleven.",
    spokenTextZh: "十一。",
    definition: "The integer equal to ten plus one; the first two-digit number with repeating digits.",
    definitionZh: "代表十加一的整數；由兩個數字1並列組成的二位數。",
    exampleSentence: "The soccer match featured eleven active players on each squad.",
    exampleSentenceZh: "綠茵球場上每一支足球隊伍共有十一位球員並肩作戰。",
    phoneticSyllables: "E · lev · en",
    clue: "The integer written as two parallel vertical strokes side by side is...",
    clueZh: "由兩個1並排書寫、排在十之後的二位數是...",
    fitzgeraldCategory: 'adjectives',
    icon: "1️⃣1️⃣",
    order: 12,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-num-12',
    categoryId: 'cat-numbers',
    label: "Twelve",
    labelZh: "十二",
    spokenText: "Twelve.",
    spokenTextZh: "十二。",
    definition: "The integer equal to ten plus two; one dozen.",
    definitionZh: "代表十加二的整數；傳統計量的一打，也是時鐘面上的總點數。",
    exampleSentence: "The bakery packaged a full dozen warm rolls in the box.",
    exampleSentenceZh: "麵包坊在紙盒裡整整齊齊裝滿了一打香噴噴的現烤餐包。",
    phoneticSyllables: "Twelve",
    clue: "The count of hours on a round clock face or a full dozen is...",
    clueZh: "傳統時鐘表面上指針繞一圈的最高點數、亦稱一打的是...",
    fitzgeraldCategory: 'adjectives',
    icon: "1️⃣2️⃣",
    order: 13,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-num-13',
    categoryId: 'cat-numbers',
    label: "Thirteen",
    labelZh: "十三",
    spokenText: "Thirteen.",
    spokenTextZh: "十三。",
    definition: "The prime number equal to twelve plus one.",
    definitionZh: "代表十二加一的質數二位數。",
    exampleSentence: "A baker's dozen includes thirteen fresh pastries.",
    exampleSentenceZh: "烘焙坊的貼心優惠常在十二個麵包外多贈送一個凑足此數。",
    phoneticSyllables: "Thir · teen",
    clue: "The integer immediately following twelve, often called a baker's dozen.",
    clueZh: "排在十二後面的質數整數，烘焙師傅常多給一個凑成此數。",
    fitzgeraldCategory: 'adjectives',
    icon: "1️⃣3️⃣",
    order: 14,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-num-14',
    categoryId: 'cat-numbers',
    label: "Fourteen",
    labelZh: "十四",
    spokenText: "Fourteen.",
    spokenTextZh: "十四。",
    definition: "The integer equal to ten plus four; the count of days in two weeks (a fortnight).",
    definitionZh: "代表十加四的整數；剛好等於雙週（十四天）的總天數。",
    exampleSentence: "The vacation retreat lasted for exactly two weeks.",
    exampleSentenceZh: "這趟悠閒的避暑假期一共度過了整整兩週的時間。",
    phoneticSyllables: "Four · teen",
    clue: "The total count of days in two full weeks is...",
    clueZh: "兩個完整星期（雙週）所包含的全部天數總和是...",
    fitzgeraldCategory: 'adjectives',
    icon: "1️⃣4️⃣",
    order: 15,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-num-15',
    categoryId: 'cat-numbers',
    label: "Fifteen",
    labelZh: "十五",
    spokenText: "Fifteen.",
    spokenTextZh: "十五。",
    definition: "The integer equal to ten plus five; a quarter of an hour in minutes.",
    definitionZh: "代表十加五的整數；一小時四分之一（十五分鐘）的時間單位。",
    exampleSentence: "He took a gentle break for fifteen minutes between exercises.",
    exampleSentenceZh: "他在兩項伸展活動之間安排了一刻鐘（十五分鐘）的放鬆休息。",
    phoneticSyllables: "Fif · teen",
    clue: "The count of minutes in a quarter of an hour is...",
    clueZh: "一刻鐘所代表的分鐘數、等於一小時的四分之一的是...",
    fitzgeraldCategory: 'adjectives',
    icon: "1️⃣5️⃣",
    order: 16,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-num-16',
    categoryId: 'cat-numbers',
    label: "Sixteen",
    labelZh: "十六",
    spokenText: "Sixteen.",
    spokenTextZh: "十六。",
    definition: "The integer equal to fifteen plus one; four squared.",
    definitionZh: "代表十五加一的整數；四的平方（4x4）。",
    exampleSentence: "The tournament grid began with sixteen competitive contenders.",
    exampleSentenceZh: "棋藝邀請賽在十六位選手的精采對弈中拉開序幕。",
    phoneticSyllables: "Six · teen",
    clue: "The square of four multiplied by four is...",
    clueZh: "四乘以四所得到的乘積、排在十五後面的是...",
    fitzgeraldCategory: 'adjectives',
    icon: "1️⃣6️⃣",
    order: 17,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-num-17',
    categoryId: 'cat-numbers',
    label: "Seventeen",
    labelZh: "十七",
    spokenText: "Seventeen.",
    spokenTextZh: "十七。",
    definition: "The prime integer equal to sixteen plus one.",
    definitionZh: "代表十六加一的質數整數。",
    exampleSentence: "He celebrated his grandson's seventeenth birthday with a family cake.",
    exampleSentenceZh: "全家人齊聚一堂為孫子慶祝青春洋溢的生日。",
    phoneticSyllables: "Sev · en · teen",
    clue: "The prime integer between sixteen and eighteen is...",
    clueZh: "排在十六與十八之間的二位數質數是...",
    fitzgeraldCategory: 'adjectives',
    icon: "1️⃣7️⃣",
    order: 18,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-num-18',
    categoryId: 'cat-numbers',
    label: "Eighteen",
    labelZh: "十八",
    spokenText: "Eighteen.",
    spokenTextZh: "十八。",
    definition: "The integer equal to seventeen plus one; the age of adulthood in many cultures.",
    definitionZh: "代表十七加一的整數；許多地區代表成年的年齡指標。",
    exampleSentence: "A standard championship golf course features eighteen distinct holes.",
    exampleSentenceZh: "一座標準高爾夫球場總共設有十八個各有特色的球洞。",
    phoneticSyllables: "Eigh · teen",
    clue: "The total count of holes on a championship golf course is...",
    clueZh: "一座標準高爾夫球場所擁有的球洞總數是...",
    fitzgeraldCategory: 'adjectives',
    icon: "1️⃣8️⃣",
    order: 19,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-num-19',
    categoryId: 'cat-numbers',
    label: "Nineteen",
    labelZh: "十九",
    spokenText: "Nineteen.",
    spokenTextZh: "十九。",
    definition: "The integer equal to eighteen plus one; the last teenage integer.",
    definitionZh: "代表十八加一的質數整數；雙位數十位數為1的最後一個數字。",
    exampleSentence: "The bus line stopped at nineteen different neighborhood stations.",
    exampleSentenceZh: "這班社區公車沿線停靠了十九個方便居民上下車的站點。",
    phoneticSyllables: "Nine · teen",
    clue: "The final integer ending in teen right before twenty is...",
    clueZh: "排在二十正前方、最後一個以十開頭的數字是...",
    fitzgeraldCategory: 'adjectives',
    icon: "1️⃣9️⃣",
    order: 20,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-num-20',
    categoryId: 'cat-numbers',
    label: "Twenty",
    labelZh: "二十",
    spokenText: "Twenty.",
    spokenTextZh: "二十。",
    definition: "The integer equal to two tens; twice ten.",
    definitionZh: "代表兩個十（2x10）相加的整數；「二十」。",
    exampleSentence: "The rehabilitation warm-up routine consisted of twenty gentle knee lifts.",
    exampleSentenceZh: "早晨的伸展熱身包含二十次輕鬆安全的抬膝運動。",
    phoneticSyllables: "Twen · ty",
    clue: "The integer equal to two times ten is...",
    clueZh: "十的兩倍、也是二個十相加的整數是...",
    fitzgeraldCategory: 'adjectives',
    icon: "2️⃣0️⃣",
    order: 21,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-num-30',
    categoryId: 'cat-numbers',
    label: "Thirty",
    labelZh: "三十",
    spokenText: "Thirty.",
    spokenTextZh: "三十。",
    definition: "The integer equal to three tens; thirty.",
    definitionZh: "代表三個十（3x10）相加的整數；「三十」。",
    exampleSentence: "A standard month on the calendar contains thirty days.",
    exampleSentenceZh: "日曆上多數月份大約都包含三十天左右的光陰。",
    phoneticSyllables: "Thir · ty",
    clue: "The count of minutes in half an hour is...",
    clueZh: "等於半個小時的分鐘長度、也是多數月份天數的是...",
    fitzgeraldCategory: 'adjectives',
    icon: "3️⃣0️⃣",
    order: 22,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-num-100',
    categoryId: 'cat-numbers',
    label: "Hundred",
    labelZh: "百",
    spokenText: "One hundred.",
    spokenTextZh: "一百。",
    definition: "The integer equal to ten times ten; one hundred; a century in years.",
    definitionZh: "代表十個十（10x10）相乘的整數；「一百」；一個世紀的年數。",
    exampleSentence: "He received a perfect full score of one hundred on his memory evaluation.",
    exampleSentenceZh: "他在記憶評估測驗中表現亮眼，拿下了滿分一百分的優異成績。",
    phoneticSyllables: "Hun · dred",
    clue: "The count of years in a full century equal to ten tens is a...",
    clueZh: "一個世紀所包含的整整歲月年數、等於十個十相乘的是...",
    fitzgeraldCategory: 'adjectives',
    icon: "1️⃣0️⃣0️⃣",
    order: 23,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
];

export const DEFAULT_VISUAL_SCENES: VisualScene[] = [
  {
    id: 'scene-livingroom',
    title: 'Living Room',
    titleZh: '客廳',
    description: 'Everyday comforts: Comfortable couch with Quorra sleeping, TV remote, side table water, reading lamp.',
    descriptionZh: '日常居家：最愛的沙發 (Quorra 睡覺中)、電視遙控器、邊桌水杯。',
    imageBlobId: 'blob-livingroom-img',
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'scene-kitchen',
    title: 'Kitchen',
    titleZh: '廚房',
    description: 'Meal prep & dining: Refrigerator, sink, coffee maker, dining table, water cup.',
    descriptionZh: '廚房與用餐：冰箱、洗水槽、咖啡機、餐桌、水杯。',
    imageBlobId: 'blob-kitchen-img',
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'scene-bedroom',
    title: 'Bedroom',
    titleZh: '臥室',
    description: 'Rest & workspace: Comfortable bed, study desk, laptop computer.',
    descriptionZh: '休息與工作：舒適大床、書桌、手提電腦。',
    imageBlobId: 'blob-bedroom-img',
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'scene-bathroom',
    title: 'Bathroom',
    titleZh: '浴室',
    description: 'Daily hygiene: Toilet, walk-in shower, wash sink, toothbrush.',
    descriptionZh: '日常盥洗：馬桶、淋浴間、洗手台、牙刷。',
    imageBlobId: 'blob-bathroom-img',
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'scene-garden',
    title: 'Garden',
    titleZh: '花園',
    description: 'Outdoor nature: Warm sun, tall shade trees, blooming flowers, green grass.',
    descriptionZh: '戶外庭院：溫暖陽光、綠蔭大樹、盛開花圃、綠油油草地。',
    imageBlobId: 'blob-garden-img',
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
];

export const DEFAULT_HOTSPOTS: VisualSceneHotspot[] = [
  // Living Room hotspots
  {
    id: 'hs-chair',
    sceneId: 'scene-livingroom',
    x: 10,
    y: 32,
    width: 26,
    height: 18,
    label: 'Couch',
    labelZh: '沙發休息',
    spokenText: 'I would like to sit comfortably on the couch.',
    spokenTextZh: '我想坐在舒適的沙發上休息。',
    color: '#3B82F6',
  },
  {
    id: 'hs-pet-quorra',
    sceneId: 'scene-livingroom',
    x: 19,
    y: 50,
    width: 25,
    height: 38,
    label: 'Quorra',
    labelZh: '狗兒 Quorra 🐕',
    spokenText: 'Good girl, Quorra. I want to pet you.',
    spokenTextZh: '好乖的 Quorra，我想摸摸妳。',
    color: '#F59E0B',
  },
  {
    id: 'hs-remote',
    sceneId: 'scene-livingroom',
    x: 52,
    y: 50,
    width: 18,
    height: 20,
    label: 'TV Remote',
    labelZh: '電視遙控器',
    spokenText: 'Can you please hand me the TV remote control?',
    spokenTextZh: '請幫我拿電視遙控器。',
    color: '#10B981',
  },
  {
    id: 'hs-water-table',
    sceneId: 'scene-livingroom',
    x: 75,
    y: 45,
    width: 20,
    height: 30,
    label: 'Water Cup',
    labelZh: '邊桌水杯',
    spokenText: 'Please pass me my cup of water from the side table.',
    spokenTextZh: '請把邊桌上的水杯拿給我。',
    color: '#F59E0B',
  },
  // Kitchen hotspots
  {
    id: 'hs-fridge',
    sceneId: 'scene-kitchen',
    x: 3.5,
    y: 14,
    width: 14,
    height: 56,
    label: 'Refrigerator',
    labelZh: '冰箱',
    spokenText: 'Let us check the refrigerator for food or a drink.',
    spokenTextZh: '我們去冰箱找點食物或飲料。',
    color: '#0284C7',
  },
  {
    id: 'hs-coffee-pot',
    sceneId: 'scene-kitchen',
    x: 19,
    y: 24,
    width: 13,
    height: 24,
    label: 'Coffee Maker',
    labelZh: '熱咖啡壺',
    spokenText: 'Can I have a fresh cup of warm coffee or tea, please?',
    spokenTextZh: '我想喝杯熱咖啡或溫茶。',
    color: '#8B5CF6',
  },
  {
    id: 'hs-kitchen-sink',
    sceneId: 'scene-kitchen',
    x: 33,
    y: 27,
    width: 14,
    height: 24,
    label: 'Kitchen Sink',
    labelZh: '洗水槽',
    spokenText: 'I need to use the kitchen sink to wash hands or dishes.',
    spokenTextZh: '我想用廚房洗水槽洗手或洗碗。',
    color: '#06B6D4',
  },
  {
    id: 'hs-dining-table',
    sceneId: 'scene-kitchen',
    x: 52.5,
    y: 44,
    width: 29,
    height: 36,
    label: 'Dining Table',
    labelZh: '用餐餐桌',
    spokenText: 'I am ready to eat a meal at the dining table.',
    spokenTextZh: '我想在餐桌前坐下來吃飯。',
    color: '#F59E0B',
  },
  {
    id: 'hs-kitchen-water',
    sceneId: 'scene-kitchen',
    x: 82.5,
    y: 46,
    width: 13,
    height: 32,
    label: 'Water Cup',
    labelZh: '餐桌水杯',
    spokenText: 'Please pass me my cup of water from the dining table.',
    spokenTextZh: '請把餐桌上的水杯拿給我。',
    color: '#0284C7',
  },
  // Bedroom hotspots
  {
    id: 'hs-bed',
    sceneId: 'scene-bedroom',
    x: 5,
    y: 34,
    width: 42,
    height: 50,
    label: 'Bed',
    labelZh: '臥室大床',
    spokenText: 'I would like to lie down and rest in bed.',
    spokenTextZh: '我想去床上躺下來休息。',
    color: '#6366F1',
  },
  {
    id: 'hs-desk',
    sceneId: 'scene-bedroom',
    x: 53,
    y: 48,
    width: 42,
    height: 42,
    label: 'Desk',
    labelZh: '書桌',
    spokenText: 'I would like to sit at the desk.',
    spokenTextZh: '我想坐在書桌前。',
    color: '#F59E0B',
  },
  {
    id: 'hs-laptop',
    sceneId: 'scene-bedroom',
    x: 57,
    y: 30,
    width: 17,
    height: 21,
    label: 'Laptop',
    labelZh: '筆記型電腦',
    spokenText: 'Can you please open my laptop computer?',
    spokenTextZh: '請幫我打開手提電腦。',
    color: '#10B981',
  },
  {
    id: 'hs-ipad',
    sceneId: 'scene-bedroom',
    x: 76,
    y: 32,
    width: 15,
    height: 19,
    label: 'iPad',
    labelZh: 'iPad 平板電腦',
    spokenText: 'Can you please hand me my iPad tablet?',
    spokenTextZh: '請幫我拿我的 iPad 平板電腦。',
    color: '#06B6D4',
  },
  // Bathroom hotspots
  {
    id: 'hs-toilet',
    sceneId: 'scene-bathroom',
    x: 5,
    y: 31,
    width: 18,
    height: 53,
    label: 'Toilet',
    labelZh: '馬桶',
    spokenText: 'I need to use the toilet, please assist me.',
    spokenTextZh: '我想上廁所，請協助我。',
    color: '#3B82F6',
  },
  {
    id: 'hs-shower',
    sceneId: 'scene-bathroom',
    x: 26,
    y: 11,
    width: 28,
    height: 73,
    label: 'Shower',
    labelZh: '淋浴間',
    spokenText: 'I would like to take a warm shower.',
    spokenTextZh: '我想去洗個熱水澡。',
    color: '#06B6D4',
  },
  {
    id: 'hs-bathroom-sink',
    sceneId: 'scene-bathroom',
    x: 57,
    y: 33,
    width: 37,
    height: 52,
    label: 'Wash Sink',
    labelZh: '洗手台',
    spokenText: 'I want to wash my hands and face at the sink.',
    spokenTextZh: '我想在洗手台洗手和洗臉。',
    color: '#10B981',
  },
  {
    id: 'hs-toothbrush',
    sceneId: 'scene-bathroom',
    x: 83,
    y: 24,
    width: 12,
    height: 23,
    label: 'Toothbrush',
    labelZh: '牙刷',
    spokenText: 'I need my toothbrush to brush my teeth.',
    spokenTextZh: '請幫我拿牙刷，我想刷牙。',
    color: '#EC4899',
  },
  // Garden hotspots
  {
    id: 'hs-sun',
    sceneId: 'scene-garden',
    x: 72,
    y: 6,
    width: 22,
    height: 24,
    label: 'Sun',
    labelZh: '溫暖太陽',
    spokenText: 'I would like to sit in the warm sun outside.',
    spokenTextZh: '我想在外面曬曬溫暖的太陽。',
    color: '#F59E0B',
  },
  {
    id: 'hs-trees',
    sceneId: 'scene-garden',
    x: 5,
    y: 12,
    width: 32,
    height: 55,
    label: 'Trees',
    labelZh: '綠蔭大樹',
    spokenText: 'I would like to rest in the shade of the trees.',
    spokenTextZh: '我想在樹蔭下乘涼休息。',
    color: '#10B981',
  },
  {
    id: 'hs-flowers',
    sceneId: 'scene-garden',
    x: 42,
    y: 48,
    width: 26,
    height: 32,
    label: 'Flowers',
    labelZh: '盛開花圃',
    spokenText: 'Let us look at the beautiful blooming flowers.',
    spokenTextZh: '我們來看看美麗盛開的花朵。',
    color: '#EC4899',
  },
  {
    id: 'hs-grass',
    sceneId: 'scene-garden',
    x: 70,
    y: 55,
    width: 26,
    height: 32,
    label: 'Grass',
    labelZh: '草地',
    spokenText: 'I would like to go for a gentle walk on the grass lawn.',
    spokenTextZh: '我想在草地上散散步。',
    color: '#22C55E',
  },
];

