import type { 
  AACCategory, 
  AACCard, 
  VisualScene, 
  VisualSceneHotspot, 
  AppSettings 
} from '../../types/index.ts';

export const DEFAULT_SETTINGS: AppSettings = {
    id: 'current',
  theme: 'dark',
  gridCols: 4,
  tapDebounceMs: 300,
  speechRate: 0.9,
  speechPitch: 1.0,
  selectedVoiceURI: '',
  selectedVoiceEnUS: '',
  selectedVoiceZhTW: '',
  cardSpeechLanguage: 'en-then-zh',
  weeklyFocusCardsPerCategory: 2,
  fontSize: 'large',
  googleSheetSyncUrl: 'https://docs.google.com/spreadsheets/d/1MsCXaC6F-uJiiYsqnS4-abW2nFTYFyTMd09hHRfwOwE/edit',
  googleSheetAutoSyncOnLoad: true,
  googleSheetSyncCardsTab: 'Cards',
};

export const DEFAULT_CATEGORIES: AACCategory[] = [
  { id: 'cat-needs', name: 'Daily Needs', nameZh: '日常需求', icon: 'HeartHandshake', color: '#86EFAC', order: 1, isDefault: true },
  { id: 'cat-health', name: 'Health', nameZh: '健康身體', icon: 'Activity', color: '#EF4444', order: 2, isDefault: true },
  { id: 'cat-food', name: 'Food & Drink', nameZh: '飲食點心', icon: 'Utensils', color: '#FDBA74', order: 3, isDefault: true },
  { id: 'cat-feelings', name: 'Feelings', nameZh: '心情感受', icon: 'Smile', color: '#93C5FD', order: 4, isDefault: true },
  { id: 'cat-family', name: 'Family', nameZh: '家人親友', icon: 'Users', color: '#FDE047', order: 5, isDefault: true },
  { id: 'cat-time', name: 'Date & Time', nameZh: '時間日期', icon: 'Clock', color: '#67E8F9', order: 6, isDefault: true },
  { id: 'cat-numbers', name: 'Numbers', nameZh: '數字', icon: 'Hash', color: '#F472B6', order: 7, isDefault: true },
  { id: 'cat-activities', name: 'Activities', nameZh: '休閒活動', icon: 'Sparkles', color: '#C4B5FD', order: 8, isDefault: true },
  { id: 'cat-places', name: 'Places', nameZh: '地點場所', icon: 'MapPin', color: '#FCA5A5', order: 9, isDefault: true },
];

export const DEFAULT_CARDS: AACCard[] = [
  // --- Daily Needs ---
  {
    id: 'card-water',
    categoryId: 'cat-needs',
    label: 'Water',
    labelZh: '水 / 喝水',
    spokenText: 'I would like some water, please.',
    spokenTextZh: '請給我一杯水。',
    phoneticSyllables: 'Wa · ter',
    clue: "Drink when thirsty.",
    clueZh: "口渴時喝的",
    fitzgeraldCategory: 'nouns',
    icon: '💧🥛',
    order: 1,
    isFavorite: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-bathroom',
    categoryId: 'cat-needs',
    label: 'Bathroom',
    labelZh: '洗手間 / 廁所',
    spokenText: 'I need to use the bathroom.',
    spokenTextZh: '我想去洗手間。',
    phoneticSyllables: 'Bath · room',
    clue: "This is the room where you use the toilet.",
    clueZh: "這是上廁所的地方。",
    fitzgeraldCategory: 'emergency',
    icon: '🚻🚽',
    order: 2,
    isFavorite: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-glasses',
    categoryId: 'cat-needs',
    label: 'Glasses',
    labelZh: '眼鏡',
    spokenText: 'Can you please help me find my glasses?',
    spokenTextZh: '請幫我拿眼鏡。',
    phoneticSyllables: 'Glass · es',
    clue: "You wear these on your face to see clearly.",
    clueZh: "戴上這個可以看得很清楚。",
    fitzgeraldCategory: 'nouns',
    icon: '👓👀',
    order: 3,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-rest',
    categoryId: 'cat-needs',
    label: 'Rest / Nap',
    labelZh: '休息 / 睡覺',
    spokenText: 'I am feeling tired and need to rest.',
    spokenTextZh: '我想休息一下。',
    phoneticSyllables: 'Rest',
    clue: "You do this when your body feels tired.",
    clueZh: "身體累了要好好休息睡覺。",
    fitzgeraldCategory: 'verbs',
    icon: '🛏️💤',
    order: 4,
    isFavorite: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-blanket',
    categoryId: 'cat-needs',
    label: 'Blanket',
    labelZh: '毛毯 / 被子',
    spokenText: 'I am cold, please give me a blanket.',
    spokenTextZh: '我覺得冷，請給我被子。',
    phoneticSyllables: 'Blan · ket',
    clue: "This covers you in bed to keep you warm.",
    clueZh: "把這條被子蓋在身上可以保暖。",
    fitzgeraldCategory: 'nouns',
    icon: '🛌🧣',
    order: 5,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-reposition',
    categoryId: 'cat-needs',
    label: 'Reposition',
    labelZh: '調整姿勢',
    spokenText: 'Please help me adjust my seating position.',
    spokenTextZh: '請幫我調整一下姿勢。',
    phoneticSyllables: 'Re · po · si · tion',
    clue: "This changes how you are sitting or lying down.",
    clueZh: "這樣可以幫忙調整坐著或躺著的姿勢。",
    fitzgeraldCategory: 'verbs',
    icon: '🪑🔄',
    order: 6,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },

  // --- Health & Body ---
  {
    id: 'card-pain',
    categoryId: 'cat-health',
    label: 'I Have Pain',
    labelZh: '我不舒服 / 痛',
    spokenText: 'I am experiencing pain right now.',
    spokenTextZh: '我現在覺得痛。',
    phoneticSyllables: 'Pain',
    clue: "This tells someone that a part of your body hurts.",
    clueZh: "這個表示身體有地方在痛或不舒服。",
    fitzgeraldCategory: 'emergency',
    icon: '🤕⚡',
    order: 1,
    isFavorite: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-medicine',
    categoryId: 'cat-health',
    label: 'Medicine',
    labelZh: '吃藥',
    spokenText: 'Is it time for my medication?',
    spokenTextZh: '該吃藥了嗎？',
    phoneticSyllables: 'Med · i · cine',
    clue: "You take these pills to help you feel better.",
    clueZh: "生病時要吃這些藥來讓身體好起來。",
    fitzgeraldCategory: 'nouns',
    icon: '💊💧',
    order: 2,
    isFavorite: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-dizzy',
    categoryId: 'cat-health',
    label: 'Dizzy',
    labelZh: '頭暈',
    spokenText: 'I am feeling dizzy and lightheaded.',
    spokenTextZh: '我感覺有點頭暈。',
    phoneticSyllables: 'Diz · zy',
    clue: "This is when your head feels like it is spinning.",
    clueZh: "這是頭腦昏昏沈沈在旋轉的感覺。",
    fitzgeraldCategory: 'adjectives',
    icon: '😵‍💫💫',
    order: 3,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-numbness',
    categoryId: 'cat-health',
    label: 'Numbness / Weak',
    labelZh: '發麻 / 無力',
    spokenText: 'My arm or leg feels numb or weak.',
    spokenTextZh: '我的手腳發麻沒力氣。',
    phoneticSyllables: 'Numb · ness',
    clue: "This is when your arms or legs feel weak or tingling.",
    clueZh: "這是手腳發麻沒有力氣的感覺。",
    fitzgeraldCategory: 'adjectives',
    icon: '⚡🦵',
    order: 4,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-doctor',
    categoryId: 'cat-health',
    label: 'Doctor / Nurse',
    labelZh: '醫生 / 護理師',
    spokenText: 'Please call the nurse or doctor.',
    spokenTextZh: '請叫醫生或護理師。',
    phoneticSyllables: 'Doc · tor',
    clue: "This person takes care of your health and medical needs.",
    clueZh: "這位專業人員會照顧您的身體健康。",
    fitzgeraldCategory: 'people',
    icon: '👨‍⚕️🩺',
    order: 5,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },

  // --- Food & Drink ---
  {
    id: 'card-breakfast',
    categoryId: 'cat-food',
    label: 'Breakfast',
    labelZh: '早餐',
    spokenText: 'I would like to have breakfast.',
    spokenTextZh: '我想吃早餐。',
    phoneticSyllables: 'Break · fast',
    clue: "This is the first meal you eat in the morning.",
    clueZh: "這是早上吃的第一餐。",
    fitzgeraldCategory: 'nouns',
    icon: '🍳🥞',
    order: 1,
    isFavorite: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-lunch',
    categoryId: 'cat-food',
    label: 'Lunch',
    labelZh: '午餐',
    spokenText: 'I would like to have lunch.',
    spokenTextZh: '我想吃午餐。',
    phoneticSyllables: 'Lunch',
    clue: "This is the meal you eat in the middle of the day.",
    clueZh: "這是中午吃的一餐。",
    fitzgeraldCategory: 'nouns',
    icon: '🍱🍲',
    order: 2,
    isFavorite: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-dinner',
    categoryId: 'cat-food',
    label: 'Dinner',
    labelZh: '晚餐',
    spokenText: 'I would like to have dinner.',
    spokenTextZh: '我想吃晚餐。',
    phoneticSyllables: 'Din · ner',
    clue: "This is the evening meal you eat before bedtime.",
    clueZh: "這是晚上睡前吃的一餐。",
    fitzgeraldCategory: 'nouns',
    icon: '🍽️🍲',
    order: 3,
    isFavorite: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-hungry',
    categoryId: 'cat-food',
    label: 'Hungry',
    labelZh: '肚子餓',
    spokenText: 'I am hungry and ready to eat.',
    spokenTextZh: '我肚子餓了，想吃東西。',
    phoneticSyllables: 'Hun · gry',
    clue: "Your stomach feels empty and you want to eat.",
    clueZh: "您的肚子空了想要吃東西。",
    fitzgeraldCategory: 'adjectives',
    icon: '🍽️🤤',
    order: 4,
    isFavorite: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-thirsty',
    categoryId: 'cat-food',
    label: 'Thirsty',
    labelZh: '口渴',
    spokenText: 'I am very thirsty.',
    spokenTextZh: '我口渴了。',
    phoneticSyllables: 'Thirs · ty',
    clue: "Your mouth feels dry and you want something to drink.",
    clueZh: "您的喉嚨乾乾的想要喝水。",
    fitzgeraldCategory: 'adjectives',
    icon: '🥤💧',
    order: 5,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-rice',
    categoryId: 'cat-food',
    label: 'Rice / Meal',
    labelZh: '白飯 / 吃飯',
    spokenText: 'I would like to have rice or a meal.',
    spokenTextZh: '請準備飯菜，我想吃飯。',
    phoneticSyllables: 'Rice · Meal',
    clue: "This is a warm bowl of cooked white grains.",
    clueZh: "這是一碗熱騰騰煮熟的白飯。",
    fitzgeraldCategory: 'nouns',
    icon: '🍚🥢',
    order: 6,
    isFavorite: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-pork',
    categoryId: 'cat-food',
    label: 'Pork',
    labelZh: '豬肉',
    spokenText: 'I would like some pork, please.',
    spokenTextZh: '我想吃豬肉。',
    phoneticSyllables: 'Pork',
    clue: "This is tasty meat that comes from a pig.",
    clueZh: "這是煮好的一道豬肉料理。",
    fitzgeraldCategory: 'nouns',
    icon: '🥩🐖',
    order: 7,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-beef',
    categoryId: 'cat-food',
    label: 'Beef',
    labelZh: '牛肉',
    spokenText: 'I would like some beef, please.',
    spokenTextZh: '我想吃牛肉。',
    phoneticSyllables: 'Beef',
    clue: "This is flavorful red meat that comes from cattle.",
    clueZh: "這是美味營養的牛肉料理。",
    fitzgeraldCategory: 'nouns',
    icon: '🥩🐂',
    order: 8,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-chicken',
    categoryId: 'cat-food',
    label: 'Chicken',
    labelZh: '雞肉',
    spokenText: 'I would like some chicken, please.',
    spokenTextZh: '我想吃雞肉。',
    phoneticSyllables: 'Chick · en',
    clue: "This is tender white poultry meat to eat.",
    clueZh: "這是鮮嫩好吃的雞肉料理。",
    fitzgeraldCategory: 'nouns',
    icon: '🍗🐔',
    order: 9,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-fish',
    categoryId: 'cat-food',
    label: 'Fish',
    labelZh: '魚肉',
    spokenText: 'I would like some fish, please.',
    spokenTextZh: '我想吃魚肉。',
    phoneticSyllables: 'Fish',
    clue: "This is healthy seafood that swims in the water.",
    clueZh: "這是水中游的健康魚肉料理。",
    fitzgeraldCategory: 'nouns',
    icon: '🐟🍽️',
    order: 10,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-soup',
    categoryId: 'cat-food',
    label: 'Soup',
    labelZh: '喝湯',
    spokenText: 'Some warm soup sounds good.',
    spokenTextZh: '我想喝點熱湯。',
    phoneticSyllables: 'Soup',
    clue: "This is warm broth served in a bowl.",
    clueZh: "這是一碗熱呼呼好喝的熱湯。",
    fitzgeraldCategory: 'nouns',
    icon: '🍲🥄',
    order: 11,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-salad',
    categoryId: 'cat-food',
    label: 'Salad',
    labelZh: '沙拉',
    spokenText: 'I would like some salad, please.',
    spokenTextZh: '我想吃沙拉。',
    phoneticSyllables: 'Sal · ad',
    clue: "This is a bowl of fresh crisp green vegetables.",
    clueZh: "這是一盤新鮮清爽的蔬菜沙拉。",
    fitzgeraldCategory: 'nouns',
    icon: '🥗🥬',
    order: 12,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-fruit',
    categoryId: 'cat-food',
    label: 'Fruit',
    labelZh: '水果',
    spokenText: 'Can I have some fruit, please?',
    spokenTextZh: '我想吃點水果。',
    phoneticSyllables: 'Fruit',
    clue: "These are sweet healthy foods like apples and oranges.",
    clueZh: "這是香甜新鮮又營養的水果。",
    fitzgeraldCategory: 'nouns',
    icon: '🍎🍌',
    order: 13,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-warm-water',
    categoryId: 'cat-food',
    label: 'Warm Water',
    labelZh: '溫開水',
    spokenText: 'Please give me a cup of warm water.',
    spokenTextZh: '請給我一杯溫開水。',
    phoneticSyllables: 'Warm · Wa · ter',
    clue: "This is comfortable water that is heated and soothing.",
    clueZh: "這是一杯溫度適中的溫開水。",
    fitzgeraldCategory: 'nouns',
    icon: '🫖♨️',
    order: 14,
    isFavorite: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-coffee',
    categoryId: 'cat-food',
    label: 'Coffee / Tea',
    labelZh: '咖啡 / 茶',
    spokenText: 'I would love a warm cup of coffee or tea.',
    spokenTextZh: '我想喝杯溫茶或咖啡。',
    phoneticSyllables: 'Cof · fee · Tea',
    clue: "This is a hot aromatic brewed beverage in a mug.",
    clueZh: "這是一杯香濃溫熱的咖啡或茶。",
    fitzgeraldCategory: 'nouns',
    icon: '☕🍵',
    order: 15,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-milk',
    categoryId: 'cat-food',
    label: 'Milk',
    labelZh: '牛奶',
    spokenText: 'I would like some milk, please.',
    spokenTextZh: '我想喝牛奶。',
    phoneticSyllables: 'Milk',
    clue: "This is a nutritious white dairy drink rich in calcium.",
    clueZh: "這是一杯營養豐富的香濃白牛奶。",
    fitzgeraldCategory: 'nouns',
    icon: '🥛🐄',
    order: 16,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-cut-food',
    categoryId: 'cat-food',
    label: 'Cut Small Pieces',
    labelZh: '切小塊一點',
    spokenText: 'Please cut the food into smaller pieces for me.',
    spokenTextZh: '請幫我把食物切小塊一點。',
    phoneticSyllables: 'Cut · Small · Piec · es',
    clue: "This asks someone to cut your meal into small bites.",
    clueZh: "這表示需要把食物切成容易吞嚥的小塊。",
    fitzgeraldCategory: 'verbs',
    icon: '🔪🍽️',
    order: 17,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-too-hot',
    categoryId: 'cat-food',
    label: 'Too Hot',
    labelZh: '太燙了',
    spokenText: 'This is too hot, please let it cool down.',
    spokenTextZh: '這個太燙了，請放涼一點。',
    phoneticSyllables: 'Too · Hot',
    clue: "This food or drink needs time to cool down.",
    clueZh: "這道食物太燙了需要先放涼一下。",
    fitzgeraldCategory: 'adjectives',
    icon: '♨️🥵',
    order: 18,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-too-cold',
    categoryId: 'cat-food',
    label: 'Too Cold / Warm Up',
    labelZh: '太冷了 / 加熱',
    spokenText: 'This is cold, can you please warm it up?',
    spokenTextZh: '這個變冷了，可以幫我加熱嗎？',
    phoneticSyllables: 'Too · Cold',
    clue: "This food has gotten cold and needs to be heated.",
    clueZh: "食物冷掉了需要拿去重新加熱。",
    fitzgeraldCategory: 'adjectives',
    icon: '❄️🥶',
    order: 19,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-delicious',
    categoryId: 'cat-food',
    label: 'Delicious',
    labelZh: '很好吃',
    spokenText: 'This food is very delicious, thank you!',
    spokenTextZh: '這個很好吃，謝謝！',
    phoneticSyllables: 'De · li · cious',
    clue: "This tells everyone that the meal tastes wonderful.",
    clueZh: "這表示這道料理的味道非常美味好吃。",
    fitzgeraldCategory: 'social',
    icon: '😋👍',
    order: 20,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-full',
    categoryId: 'cat-food',
    label: 'Full / Finished',
    labelZh: '吃飽了',
    spokenText: 'I am full and all done eating, thank you.',
    spokenTextZh: '我吃飽了，謝謝。',
    phoneticSyllables: 'Full · Fin · ished',
    clue: "Your stomach is satisfied and you have finished eating.",
    clueZh: "肚子已經吃得飽飽的不用再吃了。",
    fitzgeraldCategory: 'social',
    icon: '✋🍽️',
    order: 21,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },

  // --- Feelings ---
  {
    id: 'card-happy',
    categoryId: 'cat-feelings',
    label: 'Happy / Good',
    labelZh: '開心 / 很好',
    spokenText: 'I am feeling good and happy today.',
    spokenTextZh: '我今天心情很好。',
    phoneticSyllables: 'Hap · py',
    clue: "You are smiling because you feel joyful and content.",
    clueZh: "您的心情很好臉上帶著微笑。",
    fitzgeraldCategory: 'adjectives',
    icon: '😊✨',
    order: 1,
    isFavorite: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-frustrated',
    categoryId: 'cat-feelings',
    label: 'Frustrated',
    labelZh: '著急 / 沮喪',
    spokenText: 'I am feeling frustrated trying to express myself.',
    spokenTextZh: '我有點著急講不清楚。',
    phoneticSyllables: 'Frus · trat · ed',
    clue: "You feel upset because something is hard to do.",
    clueZh: "事情不順利時心裡覺得有點著急沮喪。",
    fitzgeraldCategory: 'adjectives',
    icon: '😣💢',
    order: 2,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-anxious',
    categoryId: 'cat-feelings',
    label: 'Anxious / Worried',
    labelZh: '擔心 / 焦慮',
    spokenText: 'I feel a bit anxious or worried.',
    spokenTextZh: '我有點擔心不安。',
    phoneticSyllables: 'Anx · ious',
    clue: "You feel uneasy or nervous about what might happen.",
    clueZh: "心裡感到有點緊張不安與擔心。",
    fitzgeraldCategory: 'adjectives',
    icon: '😟💭',
    order: 3,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-tired',
    categoryId: 'cat-feelings',
    label: 'Tired',
    labelZh: '疲倦 / 想睡',
    spokenText: 'I am feeling tired.',
    spokenTextZh: '我感覺很累。',
    phoneticSyllables: 'Tired',
    clue: "Your body is low on energy and ready to sleep.",
    clueZh: "您的身體感到疲倦想要休息睡覺。",
    fitzgeraldCategory: 'adjectives',
    icon: '😴💤',
    order: 4,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-love',
    categoryId: 'cat-feelings',
    label: 'I Love You',
    labelZh: '我愛你',
    spokenText: 'I love you very much.',
    spokenTextZh: '我很愛你們。',
    phoneticSyllables: 'I · Love · You',
    clue: "You say this to show deep affection to someone special.",
    clueZh: "這句話表達對身邊親人深深的愛意。",
    fitzgeraldCategory: 'social',
    icon: '🥰❤️',
    order: 5,
    isFavorite: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },

  // --- Family & People ---
  {
    id: 'card-family-daughter',
    categoryId: 'cat-family',
    label: 'Daughter',
    labelZh: '女兒',
    spokenText: 'Where is my daughter?',
    spokenTextZh: '我女兒在哪裡？',
    phoneticSyllables: 'Daugh · ter',
    clue: "This is your beloved female child in the family.",
    clueZh: "這是家中貼心可愛的女兒。",
    fitzgeraldCategory: 'people',
    icon: '👩👧',
    order: 1,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-family-son',
    categoryId: 'cat-family',
    label: 'Son',
    labelZh: '兒子',
    spokenText: 'Where is my son?',
    spokenTextZh: '我兒子在哪裡？',
    phoneticSyllables: 'Son',
    clue: "This is your beloved male child in the family.",
    clueZh: "這是家中孝順懂事的兒子。",
    fitzgeraldCategory: 'people',
    icon: '👦👨',
    order: 2,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-family-spouse',
    categoryId: 'cat-family',
    label: 'Wife',
    labelZh: '太太',
    spokenText: 'Where is my wife?',
    spokenTextZh: '我太太在哪裡？',
    phoneticSyllables: 'Wife',
    clue: "This is your loving wife who stays by your side.",
    clueZh: "這是身邊陪伴照顧您的親愛太太。",
    fitzgeraldCategory: 'people',
    icon: '👵💍',
    order: 3,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-family-grandkids',
    categoryId: 'cat-family',
    label: 'Grandchildren',
    labelZh: '孫子 / 孫女',
    spokenText: 'How are the grandkids doing?',
    spokenTextZh: '孫子孫女們好嗎？',
    phoneticSyllables: 'Grand · chil · dren',
    clue: "These are the young children of your sons and daughters.",
    clueZh: "這些是您兒女所生的孫子孫女。",
    fitzgeraldCategory: 'people',
    icon: '👶🧒',
    order: 4,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-family-dog',
    categoryId: 'cat-family',
    label: 'Dog',
    labelZh: '狗狗',
    spokenText: 'Where is the dog?',
    spokenTextZh: '狗狗在哪裡？',
    phoneticSyllables: 'Dog',
    clue: "This is a loyal furry pet who barks and wags its tail.",
    clueZh: "這是搖著尾巴汪汪叫的可愛寵物狗狗。",
    fitzgeraldCategory: 'nouns',
    icon: '🐶🐾',
    order: 5,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },

  // --- Activities ---
  {
    id: 'card-tv',
    categoryId: 'cat-activities',
    label: 'Watch TV',
    labelZh: '看電視',
    spokenText: 'Can we turn on the TV or watch a show?',
    spokenTextZh: '我想看電視。',
    phoneticSyllables: 'Watch · T · V',
    clue: "You sit back and watch interesting shows on the screen.",
    clueZh: "坐在沙發上看電視螢幕上的精彩節目。",
    fitzgeraldCategory: 'verbs',
    icon: '📺👀',
    order: 1,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-music',
    categoryId: 'cat-activities',
    label: 'Music',
    labelZh: '聽音樂',
    spokenText: 'I would like to listen to some music.',
    spokenTextZh: '我想聽音樂。',
    phoneticSyllables: 'Mu · sic',
    clue: "You listen to soothing songs and pleasant melodies.",
    clueZh: "靜靜聆聽好聽優美的歌曲和旋律。",
    fitzgeraldCategory: 'nouns',
    icon: '🎵🎧',
    order: 2,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-walk',
    categoryId: 'cat-activities',
    label: 'Go for a Walk',
    labelZh: '去散步',
    spokenText: 'Can we go outside for some fresh air or a walk?',
    spokenTextZh: '我想出去走走散步。',
    phoneticSyllables: 'Go · for · a · walk',
    clue: "You stroll around on foot to get fresh air and exercise.",
    clueZh: "邁開腳步到處走走散步運動。",
    fitzgeraldCategory: 'verbs',
    icon: '🚶🌳',
    order: 3,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-read',
    categoryId: 'cat-activities',
    label: 'Read / Book',
    labelZh: '看書 / 看報',
    spokenText: 'Can you bring me something to read?',
    spokenTextZh: '請拿書或報紙給我看。',
    phoneticSyllables: 'Read · Book',
    clue: "You open a book or newspaper to read the printed words.",
    clueZh: "打開書本或報紙閱讀文字。",
    fitzgeraldCategory: 'verbs',
    icon: '📖👓',
    order: 4,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-therapy-action',
    categoryId: 'cat-activities',
    label: 'Speech Practice',
    labelZh: '語言復健',
    spokenText: 'Let us do our speech therapy exercises.',
    spokenTextZh: '我們來做語言復健練習。',
    phoneticSyllables: 'Speech · Prac · tice',
    clue: "You practice talking and exercises to strengthen your speech.",
    clueZh: "透過練習發音和說話來進行語言復健。",
    fitzgeraldCategory: 'verbs',
    icon: '🗣️🎯',
    order: 5,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },

  // --- Places ---
  {
    id: 'card-home',
    categoryId: 'cat-places',
    label: 'Home',
    labelZh: '回家',
    spokenText: 'I want to be at home.',
    spokenTextZh: '我想在家裡。',
    phoneticSyllables: 'Home',
    clue: "This is your comfortable house where you live with family.",
    clueZh: "這是與家人一起居住的溫暖舒適家庭。",
    fitzgeraldCategory: 'places',
    icon: '🏡🛋️',
    order: 1,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-bedroom',
    categoryId: 'cat-places',
    label: 'Bedroom',
    labelZh: '臥室 / 房間',
    spokenText: 'Can we go to the bedroom?',
    spokenTextZh: '我們去房間。',
    phoneticSyllables: 'Bed · room',
    clue: "This is the quiet room where your bed is located.",
    clueZh: "這是擺放睡床供您休息睡覺的安靜房間。",
    fitzgeraldCategory: 'places',
    icon: '🛏️🚪',
    order: 2,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-outside',
    categoryId: 'cat-places',
    label: 'Outside / Garden',
    labelZh: '戶外 / 花園',
    spokenText: 'I would like to sit outside in the garden.',
    spokenTextZh: '我想去花園戶外坐坐。',
    phoneticSyllables: 'Out · side',
    clue: "This is the open outdoor area under the blue sky.",
    clueZh: "這是室外空氣新鮮的花園與戶外空間。",
    fitzgeraldCategory: 'places',
    icon: '🌳🌸',
    order: 3,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-hospital',
    categoryId: 'cat-places',
    label: 'Clinic / Hospital',
    labelZh: '醫院 / 診所',
    spokenText: 'We need to go to the clinic.',
    spokenTextZh: '我們需要去醫院。',
    phoneticSyllables: 'Hos · pi · tal',
    clue: "This is the medical center where doctors examine your health.",
    clueZh: "這是看病檢查健康的醫療院所。",
    fitzgeraldCategory: 'places',
    icon: '🏥🩺',
    order: 4,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-reading',
    categoryId: 'cat-activities',
    label: 'Reading',
    labelZh: '閱讀',
    spokenText: 'I would like to read a book.',
    spokenTextZh: '我想讀書。',
    phoneticSyllables: 'Read · ing',
    clue: "This is a quiet space where you can read and learn.",
    clueZh: "這是安靜閱讀書報文章的空間。",
    fitzgeraldCategory: 'verbs',
    icon: '📖☕',
    order: 6,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-car',
    categoryId: 'cat-places',
    label: 'Car Ride',
    labelZh: '搭車兜風',
    spokenText: 'I would like to go for a drive.',
    spokenTextZh: '我想搭車出去兜風。',
    phoneticSyllables: 'Car',
    clue: "You sit inside a motor vehicle to travel on the road.",
    clueZh: "坐在汽車裡沿著馬路出門兜風。",
    fitzgeraldCategory: 'places',
    icon: '🚗💨',
    order: 5,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },

  // --- Time & Dates ---
  {
    id: 'card-time-today',
    categoryId: 'cat-time',
    label: 'Today',
    labelZh: '今天',
    spokenText: 'Today.',
    spokenTextZh: '今天。',
    phoneticSyllables: 'To · day',
    clue: "This is the present day that is happening right now.",
    clueZh: "這就是正在度過的這一天。",
    fitzgeraldCategory: 'nouns',
    icon: '📅📍',
    order: 1,
    isFavorite: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-time-tomorrow',
    categoryId: 'cat-time',
    label: 'Tomorrow',
    labelZh: '明天',
    spokenText: 'Tomorrow.',
    spokenTextZh: '明天。',
    phoneticSyllables: 'To · mor · row',
    clue: "This is the brand new day that comes after today.",
    clueZh: "這是今天過後的下一個日子。",
    fitzgeraldCategory: 'nouns',
    icon: '🌅⏭️',
    order: 2,
    isFavorite: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-time-yesterday',
    categoryId: 'cat-time',
    label: 'Yesterday',
    labelZh: '昨天',
    spokenText: 'Yesterday.',
    spokenTextZh: '昨天。',
    phoneticSyllables: 'Yes · ter · day',
    clue: "This is the day that came just before today.",
    clueZh: "這是今天剛過去的前一天。",
    fitzgeraldCategory: 'nouns',
    icon: '📆⏮️',
    order: 3,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-time-now',
    categoryId: 'cat-time',
    label: 'Now',
    labelZh: '現在 / 立刻',
    spokenText: 'Right now, please.',
    spokenTextZh: '現在。',
    phoneticSyllables: 'Now',
    clue: "This refers to the exact current moment without delay.",
    clueZh: "這代表就在眼前這個當下時刻。",
    fitzgeraldCategory: 'adjectives',
    icon: '⏱️⚡',
    order: 4,
    isFavorite: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-time-later',
    categoryId: 'cat-time',
    label: 'Later',
    labelZh: '等一下 / 稍後',
    spokenText: 'Later, please.',
    spokenTextZh: '等一下。',
    phoneticSyllables: 'La · ter',
    clue: "This will happen after a short period of time.",
    clueZh: "這件事情會稍後等一下再進行。",
    fitzgeraldCategory: 'adjectives',
    icon: '⏳🕐',
    order: 5,
    isFavorite: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-time-morning',
    categoryId: 'cat-time',
    label: 'Morning',
    labelZh: '早上 / 上午',
    spokenText: 'In the morning.',
    spokenTextZh: '早上。',
    phoneticSyllables: 'Morn · ing',
    clue: "This is the early part of the day when the sun rises.",
    clueZh: "這是太陽升起天剛亮的早晨時光。",
    fitzgeraldCategory: 'nouns',
    icon: '☀️🌅',
    order: 6,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-time-afternoon',
    categoryId: 'cat-time',
    label: 'Afternoon',
    labelZh: '下午',
    spokenText: 'In the afternoon.',
    spokenTextZh: '下午。',
    phoneticSyllables: 'Af · ter · noon',
    clue: "This is the middle part of the day between noon and evening.",
    clueZh: "這是正午過後到傍晚之間的時光。",
    fitzgeraldCategory: 'nouns',
    icon: '🌤️☕',
    order: 7,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-time-night',
    categoryId: 'cat-time',
    label: 'Night',
    labelZh: '晚上',
    spokenText: 'Tonight or at night.',
    spokenTextZh: '晚上。',
    phoneticSyllables: 'Night',
    clue: "This is the dark time of day when the stars come out.",
    clueZh: "這是天黑繁星升起準備入睡的夜晚。",
    fitzgeraldCategory: 'nouns',
    icon: '🌙⭐',
    order: 8,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  // Days of the Week
  {
    id: 'card-day-mon',
    categoryId: 'cat-time',
    label: 'Monday',
    labelZh: '星期一',
    spokenText: 'Monday.',
    spokenTextZh: '星期一。',
    phoneticSyllables: 'Mon · day',
    clue: "This is the very first workday of the standard week.",
    clueZh: "這是一週裡面的第一個工作日。",
    fitzgeraldCategory: 'nouns',
    icon: '🗓️',
    order: 9,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-day-tue',
    categoryId: 'cat-time',
    label: 'Tuesday',
    labelZh: '星期二',
    spokenText: 'Tuesday.',
    spokenTextZh: '星期二。',
    phoneticSyllables: 'Tues · day',
    clue: "This is the second day of the standard work week.",
    clueZh: "這是一週裡面的第二個工作日。",
    fitzgeraldCategory: 'nouns',
    icon: '🗓️',
    order: 10,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-day-wed',
    categoryId: 'cat-time',
    label: 'Wednesday',
    labelZh: '星期三',
    spokenText: 'Wednesday.',
    spokenTextZh: '星期三。',
    phoneticSyllables: 'Wednes · day',
    clue: "This is the middle day of the regular work week.",
    clueZh: "這是一週正中間的星期三。",
    fitzgeraldCategory: 'nouns',
    icon: '🗓️',
    order: 11,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-day-thu',
    categoryId: 'cat-time',
    label: 'Thursday',
    labelZh: '星期四',
    spokenText: 'Thursday.',
    spokenTextZh: '星期四。',
    phoneticSyllables: 'Thurs · day',
    clue: "This is the fourth day of the work week before Friday.",
    clueZh: "這是星期五前一天的星期四。",
    fitzgeraldCategory: 'nouns',
    icon: '🗓️',
    order: 12,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-day-fri',
    categoryId: 'cat-time',
    label: 'Friday',
    labelZh: '星期五',
    spokenText: 'Friday.',
    spokenTextZh: '星期五。',
    phoneticSyllables: 'Fri · day',
    clue: "This is the last workday right before the weekend begins.",
    clueZh: "這是週末放假前的最後一個工作日。",
    fitzgeraldCategory: 'nouns',
    icon: '🗓️',
    order: 13,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-day-sat',
    categoryId: 'cat-time',
    label: 'Saturday',
    labelZh: '星期六',
    spokenText: 'Saturday.',
    spokenTextZh: '星期六。',
    phoneticSyllables: 'Sat · ur · day',
    clue: "This is the first restful day of the weekend.",
    clueZh: "這是放假休息的週末第一天。",
    fitzgeraldCategory: 'nouns',
    icon: '🗓️',
    order: 14,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-day-sun',
    categoryId: 'cat-time',
    label: 'Sunday',
    labelZh: '星期日 / 週日',
    spokenText: 'Sunday.',
    spokenTextZh: '星期天。',
    phoneticSyllables: 'Sun · day',
    clue: "This is the peaceful Sunday before a new week starts.",
    clueZh: "這是新一週開始前的悠閒星期日。",
    fitzgeraldCategory: 'nouns',
    icon: '🗓️',
    order: 15,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  // Time Questions & Conversational Words
  {
    id: 'card-time-what-time',
    categoryId: 'cat-time',
    label: 'What Time?',
    labelZh: '現在幾點？',
    spokenText: 'What time is it?',
    spokenTextZh: '現在幾點了？',
    phoneticSyllables: 'What · Time',
    clue: "You ask this question to find out the current hour on the clock.",
    clueZh: "這句話用來詢問時鐘上現在是幾點幾分。",
    fitzgeraldCategory: 'social',
    icon: '🕐❓',
    order: 16,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-time-what-day',
    categoryId: 'cat-time',
    label: 'What Day?',
    labelZh: '今天星期幾？',
    spokenText: 'What day is it today?',
    spokenTextZh: '今天星期幾？',
    phoneticSyllables: 'What · Day',
    clue: "You ask this question to find out which day of the week it is.",
    clueZh: "這句話用來詢問今天到底是一週裡的星期幾。",
    fitzgeraldCategory: 'social',
    icon: '📅❓',
    order: 17,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-time-next-week',
    categoryId: 'cat-time',
    label: 'Next Week',
    labelZh: '下星期 / 下週',
    spokenText: 'Next week.',
    spokenTextZh: '下個星期。',
    phoneticSyllables: 'Next · Week',
    clue: "This is the upcoming seven-day period following this one.",
    clueZh: "這是本週過後的下一個七天循環。",
    fitzgeraldCategory: 'nouns',
    icon: '📅⏭️',
    order: 18,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-time-last-week',
    categoryId: 'cat-time',
    label: 'Last Week',
    labelZh: '上星期 / 上週',
    spokenText: 'Last week.',
    spokenTextZh: '上個星期。',
    phoneticSyllables: 'Last · Week',
    clue: "This was the seven-day period that ended before this one.",
    clueZh: "這是剛剛過去的前一個七天。",
    fitzgeraldCategory: 'nouns',
    icon: '📅⏮️',
    order: 19,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-quick-yes',
    categoryId: 'cat-needs',
    label: 'Yes / Agree',
    labelZh: '是 / 好',
    spokenText: 'Yes.',
    spokenTextZh: '是的。',
    phoneticSyllables: 'Yes',
    clue: "You say this word to express agreement or approval.",
    clueZh: "說出這個詞表示您贊成同意或點頭說好。",
    fitzgeraldCategory: 'social',
    icon: '👍✅',
    order: 7,
    isFavorite: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-quick-no',
    categoryId: 'cat-needs',
    label: 'No / Disagree',
    labelZh: '不要 / 不是',
    spokenText: 'No, thank you.',
    spokenTextZh: '不要，謝謝。',
    phoneticSyllables: 'No',
    clue: "You say this word to decline an offer or express disagreement.",
    clueZh: "說出這個詞表示您拒絕或表達不同意。",
    fitzgeraldCategory: 'social',
    icon: '👎❌',
    order: 8,
    isFavorite: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-quick-please',
    categoryId: 'cat-feelings',
    label: 'Please',
    labelZh: '請',
    spokenText: 'Please.',
    spokenTextZh: '請幫忙。',
    phoneticSyllables: 'Please',
    clue: "You use this polite word when making a kind request.",
    clueZh: "當您向別人提出請求時會用這個客氣的禮貌字。",
    fitzgeraldCategory: 'social',
    icon: '🙏✨',
    order: 6,
    isFavorite: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-quick-thanks',
    categoryId: 'cat-feelings',
    label: 'Thank You',
    labelZh: '謝謝',
    spokenText: 'Thank you very much.',
    spokenTextZh: '謝謝你。',
    phoneticSyllables: 'Thank · You',
    clue: "You say this to express your heartfelt gratitude to someone.",
    clueZh: "說出這句話用來向幫助您的人表達由衷的感謝。",
    fitzgeraldCategory: 'social',
    icon: '💐🙏',
    order: 7,
    isFavorite: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-quick-more',
    categoryId: 'cat-needs',
    label: 'More',
    labelZh: '還要 / 多一點',
    spokenText: 'I would like more, please.',
    spokenTextZh: '我還要多一點。',
    phoneticSyllables: 'More',
    clue: "You say this when you would like an extra portion of something.",
    clueZh: "當您想要再多要一點份量時會說這句話。",
    fitzgeraldCategory: 'adjectives',
    icon: '➕🤲',
    order: 9,
    isFavorite: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-quick-done',
    categoryId: 'cat-needs',
    label: 'All Done',
    labelZh: '好了 / 完成了',
    spokenText: 'I am all done.',
    spokenTextZh: '我已經好了。',
    phoneticSyllables: 'All · Done',
    clue: "You say this to tell everyone that you have finished your activity.",
    clueZh: "這表示您手邊的事情已經全部做好了。",
    fitzgeraldCategory: 'social',
    icon: '🏁👌',
    order: 10,
    isFavorite: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-quick-help',
    categoryId: 'cat-health',
    label: 'Help',
    labelZh: '請幫我',
    spokenText: 'Please help me.',
    spokenTextZh: '請幫我一下。',
    phoneticSyllables: 'Help',
    clue: "You say this when you need assistance from a caregiver.",
    clueZh: "當您需要身邊照顧者伸出援手時會說這句話。",
    fitzgeraldCategory: 'emergency',
    icon: '🆘🙋‍♂️',
    order: 6,
    isFavorite: true,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },

  // --- Numbers (0 to 9, 10, 100) ---
  {
    id: 'card-num-0',
    categoryId: 'cat-numbers',
    label: 'Zero',
    labelZh: '零',
    spokenText: 'Zero.',
    spokenTextZh: '零。',
    phoneticSyllables: 'Ze · ro',
    clue: "This is the number that represents having nothing at all.",
    clueZh: "這是代表完全沒有任何東西的數字零。",
    fitzgeraldCategory: 'adjectives',
    icon: '0️⃣',
    order: 1,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-num-1',
    categoryId: 'cat-numbers',
    label: 'One',
    labelZh: '一',
    spokenText: 'One.',
    spokenTextZh: '一。',
    phoneticSyllables: 'One',
    clue: "This is the number that represents a single item.",
    clueZh: "這是代表單一一個物品的數字一。",
    fitzgeraldCategory: 'adjectives',
    icon: '1️⃣',
    order: 2,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-num-2',
    categoryId: 'cat-numbers',
    label: 'Two',
    labelZh: '二',
    spokenText: 'Two.',
    spokenTextZh: '二。',
    phoneticSyllables: 'Two',
    clue: "This is the number that represents a matching pair.",
    clueZh: "這是代表一雙或一對的數字二。",
    fitzgeraldCategory: 'adjectives',
    icon: '2️⃣',
    order: 3,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-num-3',
    categoryId: 'cat-numbers',
    label: 'Three',
    labelZh: '三',
    spokenText: 'Three.',
    spokenTextZh: '三。',
    phoneticSyllables: 'Three',
    clue: "This is the number that is one more than two.",
    clueZh: "這是比數字二再多一個的數字三。",
    fitzgeraldCategory: 'adjectives',
    icon: '3️⃣',
    order: 4,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-num-4',
    categoryId: 'cat-numbers',
    label: 'Four',
    labelZh: '四',
    spokenText: 'Four.',
    spokenTextZh: '四。',
    phoneticSyllables: 'Four',
    clue: "This is the number that equals two plus two.",
    clueZh: "這是二加二等於四的數字四。",
    fitzgeraldCategory: 'adjectives',
    icon: '4️⃣',
    order: 5,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-num-5',
    categoryId: 'cat-numbers',
    label: 'Five',
    labelZh: '五',
    spokenText: 'Five.',
    spokenTextZh: '五。',
    phoneticSyllables: 'Five',
    clue: "This is the number of fingers you have on one hand.",
    clueZh: "這是一隻手掌上五隻手指頭的數量。",
    fitzgeraldCategory: 'adjectives',
    icon: '5️⃣',
    order: 6,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-num-6',
    categoryId: 'cat-numbers',
    label: 'Six',
    labelZh: '六',
    spokenText: 'Six.',
    spokenTextZh: '六。',
    phoneticSyllables: 'Six',
    clue: "This is the number that is one more than five.",
    clueZh: "這是比數字五再多一個的數字六。",
    fitzgeraldCategory: 'adjectives',
    icon: '6️⃣',
    order: 7,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-num-7',
    categoryId: 'cat-numbers',
    label: 'Seven',
    labelZh: '七',
    spokenText: 'Seven.',
    spokenTextZh: '七。',
    phoneticSyllables: 'Sev · en',
    clue: "This is the total number of days in one calendar week.",
    clueZh: "這是一個日曆星期包含的總天數。",
    fitzgeraldCategory: 'adjectives',
    icon: '7️⃣',
    order: 8,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-num-8',
    categoryId: 'cat-numbers',
    label: 'Eight',
    labelZh: '八',
    spokenText: 'Eight.',
    spokenTextZh: '八。',
    phoneticSyllables: 'Eight',
    clue: "This is the number that equals four plus four.",
    clueZh: "這是四加四等於八的數字八。",
    fitzgeraldCategory: 'adjectives',
    icon: '8️⃣',
    order: 9,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-num-9',
    categoryId: 'cat-numbers',
    label: 'Nine',
    labelZh: '九',
    spokenText: 'Nine.',
    spokenTextZh: '九。',
    phoneticSyllables: 'Nine',
    clue: "This is the single-digit number that is one less than ten.",
    clueZh: "這是比數字十少一個的最大個位數。",
    fitzgeraldCategory: 'adjectives',
    icon: '9️⃣',
    order: 10,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-num-10',
    categoryId: 'cat-numbers',
    label: 'Ten',
    labelZh: '十',
    spokenText: 'Ten.',
    spokenTextZh: '十。',
    phoneticSyllables: 'Ten',
    clue: "This is the total number of fingers on both of your hands.",
    clueZh: "這是雙手上所有十隻手指頭的總數。",
    fitzgeraldCategory: 'adjectives',
    icon: '🔟',
    order: 11,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-num-11',
    categoryId: 'cat-numbers',
    label: 'Eleven',
    labelZh: '十一',
    spokenText: 'Eleven.',
    spokenTextZh: '十一。',
    phoneticSyllables: 'E · lev · en',
    clue: "This is the number that equals ten plus one.",
    clueZh: "這是十加一等於十一的數字。",
    fitzgeraldCategory: 'adjectives',
    icon: '1️⃣1️⃣',
    order: 12,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-num-12',
    categoryId: 'cat-numbers',
    label: 'Twelve',
    labelZh: '十二',
    spokenText: 'Twelve.',
    spokenTextZh: '十二。',
    phoneticSyllables: 'Twelve',
    clue: "This is the total number of hours shown on a standard clock face.",
    clueZh: "這是標準時鐘錶盤上顯示的十二個小時總數。",
    fitzgeraldCategory: 'adjectives',
    icon: '1️⃣2️⃣',
    order: 13,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-num-13',
    categoryId: 'cat-numbers',
    label: 'Thirteen',
    labelZh: '十三',
    spokenText: 'Thirteen.',
    spokenTextZh: '十三。',
    phoneticSyllables: 'Thir · teen',
    clue: "This is the number that equals ten plus three.",
    clueZh: "這是十加三等於十三的數字。",
    fitzgeraldCategory: 'adjectives',
    icon: '1️⃣3️⃣',
    order: 14,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-num-14',
    categoryId: 'cat-numbers',
    label: 'Fourteen',
    labelZh: '十四',
    spokenText: 'Fourteen.',
    spokenTextZh: '十四。',
    phoneticSyllables: 'Four · teen',
    clue: "This is the number of days in two full weeks.",
    clueZh: "這是整整兩個星期包含的十四天總數。",
    fitzgeraldCategory: 'adjectives',
    icon: '1️⃣4️⃣',
    order: 15,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-num-15',
    categoryId: 'cat-numbers',
    label: 'Fifteen',
    labelZh: '十五',
    spokenText: 'Fifteen.',
    spokenTextZh: '十五。',
    phoneticSyllables: 'Fif · teen',
    clue: "This is the number that equals ten plus five.",
    clueZh: "這是十加五等於十五的數字。",
    fitzgeraldCategory: 'adjectives',
    icon: '1️⃣5️⃣',
    order: 16,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-num-16',
    categoryId: 'cat-numbers',
    label: 'Sixteen',
    labelZh: '十六',
    spokenText: 'Sixteen.',
    spokenTextZh: '十六。',
    phoneticSyllables: 'Six · teen',
    clue: "This is the number that equals ten plus six.",
    clueZh: "這是十加六等於十六的數字。",
    fitzgeraldCategory: 'adjectives',
    icon: '1️⃣6️⃣',
    order: 17,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-num-17',
    categoryId: 'cat-numbers',
    label: 'Seventeen',
    labelZh: '十七',
    spokenText: 'Seventeen.',
    spokenTextZh: '十七。',
    phoneticSyllables: 'Sev · en · teen',
    clue: "This is the number that equals ten plus seven.",
    clueZh: "這是十加七等於十七的數字。",
    fitzgeraldCategory: 'adjectives',
    icon: '1️⃣7️⃣',
    order: 18,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-num-18',
    categoryId: 'cat-numbers',
    label: 'Eighteen',
    labelZh: '十八',
    spokenText: 'Eighteen.',
    spokenTextZh: '十八。',
    phoneticSyllables: 'Eigh · teen',
    clue: "This is the number that equals ten plus eight.",
    clueZh: "這是十加八等於十八的數字。",
    fitzgeraldCategory: 'adjectives',
    icon: '1️⃣8️⃣',
    order: 19,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-num-19',
    categoryId: 'cat-numbers',
    label: 'Nineteen',
    labelZh: '十九',
    spokenText: 'Nineteen.',
    spokenTextZh: '十九。',
    phoneticSyllables: 'Nine · teen',
    clue: "This is the number that is one less than twenty.",
    clueZh: "這是比二十少一個的數字十九。",
    fitzgeraldCategory: 'adjectives',
    icon: '1️⃣9️⃣',
    order: 20,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-num-20',
    categoryId: 'cat-numbers',
    label: 'Twenty',
    labelZh: '二十',
    spokenText: 'Twenty.',
    spokenTextZh: '二十。',
    phoneticSyllables: 'Twen · ty',
    clue: "This is the number that equals two groups of ten.",
    clueZh: "這是兩組十加起來等於二十的數字。",
    fitzgeraldCategory: 'adjectives',
    icon: '2️⃣0️⃣',
    order: 21,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-num-30',
    categoryId: 'cat-numbers',
    label: 'Thirty',
    labelZh: '三十',
    spokenText: 'Thirty.',
    spokenTextZh: '三十。',
    phoneticSyllables: 'Thir · ty',
    clue: "This is the approximate number of days in one month.",
    clueZh: "這是一個月份大約擁有的三十天總數。",
    fitzgeraldCategory: 'adjectives',
    icon: '3️⃣0️⃣',
    order: 22,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'card-num-100',
    categoryId: 'cat-numbers',
    label: 'Hundred',
    labelZh: '百',
    spokenText: 'One hundred.',
    spokenTextZh: '一百。',
    phoneticSyllables: 'Hun · dred',
    clue: "This is the number that equals ten times ten.",
    clueZh: "這是十乘上十等於一百的大數字。",
    fitzgeraldCategory: 'adjectives',
    icon: '1️⃣0️⃣0️⃣',
    order: 23,
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
];

export const DEFAULT_VISUAL_SCENES: VisualScene[] = [
  {
    id: 'scene-livingroom',
    title: 'Living Room',
    titleZh: '客廳',
    description: 'Everyday comforts: Comfortable couch with Quorra sleeping, TV remote, side table water, reading lamp.',
    descriptionZh: '日常居家：最愛的沙發 (Quorra 睡覺中)、電視遙控器、邊桌水杯。',
    imageBlobId: 'blob-livingroom-img',
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'scene-kitchen',
    title: 'Kitchen',
    titleZh: '廚房',
    description: 'Meal prep & dining: Refrigerator, sink, coffee maker, dining table, water cup.',
    descriptionZh: '廚房與用餐：冰箱、洗水槽、咖啡機、餐桌、水杯。',
    imageBlobId: 'blob-kitchen-img',
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'scene-bedroom',
    title: 'Bedroom',
    titleZh: '臥室',
    description: 'Rest & workspace: Comfortable bed, study desk, laptop computer.',
    descriptionZh: '休息與工作：舒適大床、書桌、手提電腦。',
    imageBlobId: 'blob-bedroom-img',
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'scene-bathroom',
    title: 'Bathroom',
    titleZh: '浴室',
    description: 'Daily hygiene: Toilet, walk-in shower, wash sink, toothbrush.',
    descriptionZh: '日常盥洗：馬桶、淋浴間、洗手台、牙刷。',
    imageBlobId: 'blob-bathroom-img',
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
  {
    id: 'scene-garden',
    title: 'Garden',
    titleZh: '花園',
    description: 'Outdoor nature: Warm sun, tall shade trees, blooming flowers, green grass.',
    descriptionZh: '戶外庭院：溫暖陽光、綠蔭大樹、盛開花圃、綠油油草地。',
    imageBlobId: 'blob-garden-img',
    createdAt: Date.now(),
    updatedAt: Date.now(),
  },
];

export const DEFAULT_HOTSPOTS: VisualSceneHotspot[] = [
  // Living Room hotspots
  {
    id: 'hs-chair',
    sceneId: 'scene-livingroom',
    x: 12,
    y: 35,
    width: 36,
    height: 50,
    label: 'Couch',
    labelZh: '沙發 / 陪 Quorra 休息',
    spokenText: 'I would like to sit comfortably on the couch with Quorra.',
    spokenTextZh: '我想坐在舒適的沙發上，陪 Quorra 一起休息。',
    color: '#3B82F6',
  },
  {
    id: 'hs-remote',
    sceneId: 'scene-livingroom',
    x: 52,
    y: 50,
    width: 18,
    height: 20,
    label: 'TV Remote',
    labelZh: '電視遙控器',
    spokenText: 'Can you please hand me the TV remote control?',
    spokenTextZh: '請幫我拿電視遙控器。',
    color: '#10B981',
  },
  {
    id: 'hs-water-table',
    sceneId: 'scene-livingroom',
    x: 75,
    y: 45,
    width: 20,
    height: 30,
    label: 'Water Cup',
    labelZh: '邊桌水杯',
    spokenText: 'Please pass me my cup of water from the side table.',
    spokenTextZh: '請把邊桌上的水杯拿給我。',
    color: '#F59E0B',
  },
  // Kitchen hotspots
  {
    id: 'hs-fridge',
    sceneId: 'scene-kitchen',
    x: 3.5,
    y: 14,
    width: 14,
    height: 56,
    label: 'Refrigerator',
    labelZh: '冰箱',
    spokenText: 'Let us check the refrigerator for food or a drink.',
    spokenTextZh: '我們去冰箱找點食物或飲料。',
    color: '#0284C7',
  },
  {
    id: 'hs-coffee-pot',
    sceneId: 'scene-kitchen',
    x: 19,
    y: 24,
    width: 13,
    height: 24,
    label: 'Coffee Maker',
    labelZh: '熱咖啡壺 / 溫茶',
    spokenText: 'Can I have a fresh cup of warm coffee or tea, please?',
    spokenTextZh: '我想喝杯熱咖啡或溫茶。',
    color: '#8B5CF6',
  },
  {
    id: 'hs-kitchen-sink',
    sceneId: 'scene-kitchen',
    x: 33,
    y: 27,
    width: 14,
    height: 24,
    label: 'Kitchen Sink',
    labelZh: '洗水槽 / 洗手',
    spokenText: 'I need to use the kitchen sink to wash hands or dishes.',
    spokenTextZh: '我想用廚房洗水槽洗手或洗碗。',
    color: '#06B6D4',
  },
  {
    id: 'hs-dining-table',
    sceneId: 'scene-kitchen',
    x: 52.5,
    y: 44,
    width: 29,
    height: 36,
    label: 'Dining Table',
    labelZh: '餐桌 / 吃飯',
    spokenText: 'I am ready to eat a meal at the dining table.',
    spokenTextZh: '我想在餐桌前坐下來吃飯。',
    color: '#F59E0B',
  },
  {
    id: 'hs-kitchen-water',
    sceneId: 'scene-kitchen',
    x: 82.5,
    y: 46,
    width: 13,
    height: 32,
    label: 'Water Cup',
    labelZh: '水杯 / 喝水',
    spokenText: 'Please pass me my cup of water from the dining table.',
    spokenTextZh: '請把餐桌上的水杯拿給我。',
    color: '#0284C7',
  },
  // Bedroom hotspots
  {
    id: 'hs-bed',
    sceneId: 'scene-bedroom',
    x: 5,
    y: 34,
    width: 42,
    height: 50,
    label: 'Bed',
    labelZh: '床 / 躺下休息',
    spokenText: 'I would like to lie down and rest in bed.',
    spokenTextZh: '我想去床上躺下來休息。',
    color: '#6366F1',
  },
  {
    id: 'hs-desk',
    sceneId: 'scene-bedroom',
    x: 53,
    y: 48,
    width: 42,
    height: 42,
    label: 'Desk',
    labelZh: '書桌 / 桌子',
    spokenText: 'I would like to sit at the desk.',
    spokenTextZh: '我想坐在書桌前。',
    color: '#F59E0B',
  },
  {
    id: 'hs-laptop',
    sceneId: 'scene-bedroom',
    x: 57,
    y: 30,
    width: 17,
    height: 21,
    label: 'Laptop',
    labelZh: '手提電腦 / 筆電',
    spokenText: 'Can you please open my laptop computer?',
    spokenTextZh: '請幫我打開手提電腦。',
    color: '#10B981',
  },
  {
    id: 'hs-ipad',
    sceneId: 'scene-bedroom',
    x: 76,
    y: 32,
    width: 15,
    height: 19,
    label: 'iPad',
    labelZh: 'iPad 平板電腦',
    spokenText: 'Can you please hand me my iPad tablet?',
    spokenTextZh: '請幫我拿我的 iPad 平板電腦。',
    color: '#06B6D4',
  },
  // Bathroom hotspots
  {
    id: 'hs-toilet',
    sceneId: 'scene-bathroom',
    x: 5,
    y: 31,
    width: 18,
    height: 53,
    label: 'Toilet',
    labelZh: '馬桶 / 上廁所',
    spokenText: 'I need to use the toilet, please assist me.',
    spokenTextZh: '我想上廁所，請協助我。',
    color: '#3B82F6',
  },
  {
    id: 'hs-shower',
    sceneId: 'scene-bathroom',
    x: 26,
    y: 11,
    width: 28,
    height: 73,
    label: 'Shower',
    labelZh: '淋浴 / 洗澡',
    spokenText: 'I would like to take a warm shower.',
    spokenTextZh: '我想去洗個熱水澡。',
    color: '#06B6D4',
  },
  {
    id: 'hs-bathroom-sink',
    sceneId: 'scene-bathroom',
    x: 57,
    y: 33,
    width: 37,
    height: 52,
    label: 'Wash Sink',
    labelZh: '洗手台 / 洗臉',
    spokenText: 'I want to wash my hands and face at the sink.',
    spokenTextZh: '我想在洗手台洗手和洗臉。',
    color: '#10B981',
  },
  {
    id: 'hs-toothbrush',
    sceneId: 'scene-bathroom',
    x: 83,
    y: 24,
    width: 12,
    height: 23,
    label: 'Toothbrush',
    labelZh: '牙刷 / 刷牙',
    spokenText: 'I need my toothbrush to brush my teeth.',
    spokenTextZh: '請幫我拿牙刷，我想刷牙。',
    color: '#EC4899',
  },
  // Garden hotspots
  {
    id: 'hs-sun',
    sceneId: 'scene-garden',
    x: 72,
    y: 6,
    width: 22,
    height: 24,
    label: 'Sun',
    labelZh: '太陽 / 曬太陽',
    spokenText: 'I would like to sit in the warm sun outside.',
    spokenTextZh: '我想在外面曬曬溫暖的太陽。',
    color: '#F59E0B',
  },
  {
    id: 'hs-trees',
    sceneId: 'scene-garden',
    x: 5,
    y: 12,
    width: 32,
    height: 55,
    label: 'Trees',
    labelZh: '大樹 / 樹蔭',
    spokenText: 'I would like to rest in the shade of the trees.',
    spokenTextZh: '我想在樹蔭下乘涼休息。',
    color: '#10B981',
  },
  {
    id: 'hs-flowers',
    sceneId: 'scene-garden',
    x: 42,
    y: 48,
    width: 26,
    height: 32,
    label: 'Flowers',
    labelZh: '花朵 / 花圃',
    spokenText: 'Let us look at the beautiful blooming flowers.',
    spokenTextZh: '我們來看看美麗盛開的花朵。',
    color: '#EC4899',
  },
  {
    id: 'hs-grass',
    sceneId: 'scene-garden',
    x: 70,
    y: 55,
    width: 26,
    height: 32,
    label: 'Grass',
    labelZh: '草地 / 散步',
    spokenText: 'I would like to go for a gentle walk on the grass lawn.',
    spokenTextZh: '我想在草地上散散步。',
    color: '#22C55E',
  },
];
